### ISSUE TITLE
In block editor, add CTA to go to question management page

### ISSUE THREAD

**Issue by neel-a-mehta** [civiform/civiform#1005]
One common thing we saw in user testing was that Civiform admins, while building a form, want to go add questions that aren't already in the question bank. It's a bit tricky to figure out how to do that, though; they have to hit the Questions tab at the top. It would be easier if we had an "add/manage questions" button directly in the list of saved questions. It would take users straight to the Question list page, where they can add, delete, or edit questions.

**Comment by baipai** [comment]
When you talk about "It's a bit tricky to figure out how to do that, though", does it contain any technique limited or just the user experience itself?

**Comment by neel-a-mehta** [comment]
I mean that, ffor the admin, it's currently difficult to find the button to add a new question. We should try to make that button easier to find (such as by adding a similar button right on the question management page or in the question bank).

**Comment by baipai** [comment]
Is this possible or is it make sense to merge the question page (which is question management page) to the question bank? then admin can just do everything under building the form page? or it needs to be separate due to they are different systems on their own?

**Comment by neel-a-mehta** [comment]
I think the question management page has enough complexity (many different buttons) that it needs to be its own page. But you make a good point; maybe we can copy some buttons from the question management page into the question bank -- perhaps like copying the "add question" button over.

**Comment by baipai** [comment]
Leave the wrong comment to the #1013 , here is the original comment: https://github.com/seattle-uat/civiform/issues/1013#issuecomment-919067200

The reason I was trying to mention the question is because there is some conflict with adding the "+" button from the last form builder design(the one present to the city a while ago). So it is better to make the improvement based on the current staging design. (Was trying to add some record to let other people to follow, just in case the developing is start to apply the last design)

**Comment by cassandralfernandes** [comment]
Duplicate; closing in favor of #3032
