### ISSUE TITLE
Some toasts that are "success" messages are rendered like "errors"

### ISSUE THREAD

**Issue by natsid** [civiform/civiform#1176]
Currently our "error" toasts and "success" toasts look identical and they both look like errors (red). We should display happier looking toasts for success messages.

**Comment by AWBaumann** [comment]
There are 4 different types of toast messages `alert, error, success, warning`. The problem is that we never send an indicator to the views as to the severity of the issue so we're pretty much always just rendering them as errors.

Typically, our toast messages are created using a String or Optional<String> passed from the controller.
```
    if (message.isPresent()) {
      htmlBundle.addToastMessages(ToastMessage.error(message.get()).setDismissible(false));
    }
```
 
 If we can differentiate message severity (by having a more complex message object?) we could have:
 
 ```
    for (Message message : messages) {
      htmlBundle.addToastMessages(
          ToastMessage.create(message.text, message.severity).setDismissible(false));
    }
```

**Comment by natsid** [comment]
To summarize this task: As @AWBaumann mentioned, we already have the ability to use the "success" toasts that look green and successful. The problem is that in some cases we use the error toast when it should be a success toast.

**Comment by th174** [comment]
Can you give an example of a case where the error toast is being used instead of a success toast. It looks like all instances at present are using the right toast message.
