### ISSUE TITLE
When CiviForm admin creates a program, make it easier to find the program in the list

### ISSUE THREAD

**Issue by neel-a-mehta** [civiform/civiform#1238]
Right now, once you create a program, you go back to the page with a list of programs, but your new program is way at the bottom of the list -- so it's very hard to find the program. Can be confusing for admins.

Potential workarounds:

- Once you create a program, go straight to the page to edit it (or manage translations, whichever is a more natural landing point)
- Once you create a program, scroll down to the program's location in the list view
- Sort the list of programs by editing time, descending, so that the most recently added/edited programs are at the top of the list. (This is the most scalable solution IMO, and it'll also let us expand into other methods of sorting the programs list later.)

**Comment by glorialiou** [comment]
Related issues:
https://github.com/seattle-uat/civiform/issues/942

Related issues (but for the question list / submitted applications list -- could be helpful to think about lists all together):
https://github.com/seattle-uat/civiform/issues/1912
https://github.com/seattle-uat/civiform/issues/1949
https://github.com/seattle-uat/civiform/issues/944

**Comment by clouser2** [comment]
@rahaghas and I discussed this a bit today, and some immediate improvements we can make are to:

1) when creating a new program and displaying the list view, add a link to the newly created program in a toast
2) Consider auto-sorting the list by the most recently updated, so that the newly added program will be at the top

We'll also be looking into the redesign as well. The above will hopefully help make the editing experience smoother while we work on the redesign.

**Comment by clouser2** [comment]
After investigating a bit, our current infrastructure for toast messages only supports showing a string, not a secondary link as well. Plumbing this through may take a bit of work.

**Comment by clouser2** [comment]
Update: I've been focusing mainly on getting the UI mocks from https://github.com/seattle-uat/civiform/issues/1238#issuecomment-1106908001 in place. We'll likely start incrementally developing this (guarding the new UI with a query param until we've stabilized it). We're going to proceed somewhat incrementally:
  * Change layout of program cards generally for the new styling
  * Add sorting shortly after this

Currently, this page doesn't have pagination (nor does it really need to at this point, in my opinion). When implementing sort / filtering, rather than implementing all of this as server-side endpoints that require a page refresh, we can likely just do the sorting client-side in JS instead. Given that the number of programs likely won't be a scaling bottleneck, we can push this to the client and not have any need for sorting the DB entries server-side or implementing pagination.

Presently, there's no default sorting on the returned entries. We take the results from an unordered database query and feed them into Java's ImmutableSet. Given the above, I'm going to start by introducing the following sorting behavior on the existing UI:
  * Created time DESC (prefer the creation time of a draft over an active version, since it's newest)
  * Program name ASC

Note that we need a secondary sort since the created / last modified timestamps were only added recently, and there can be many programs that don't have that metadata.

Given my above assertion about client-side sorting, I'd like to proceed with implementing the default sort on the client-side rather than ordering the items returned server-side.

**Comment by clouser2** [comment]
I may actually switch to using "Last updated time" instead of "Created time" for sorting, since the latter isn't currently exposed in the UI. Adding a second date may prove more confusing than helpful. That said, there's a subtle difference between these two. As the program admin makes edits on a new draft version, last updated will be updated for each edit. If the admin was editing multiple programs, the list may be a bit unstable, which could be desirable or not depending on the admin's preference. If we sorted by created time, the new program version would pop to the top of the list on creation but wouldn't see updates as the admin made edits.

Given that we don't yet have the sorting UI, hopefully this choice will be short-lived.

**Comment by clouser2** [comment]
@elisekalstad - can you confirm whether our current plan of sorting by most recently modified program would be an improvement here? The net effect is that after creating / editing a program, it will now appear at the top of the list of programs.

**Comment by elisekalstad** [comment]
@clouser2 YES! Sorting by most recently modified is really helpful. For example, when I re-publish a form, I usually re-publish it a few times in a short period of time as we test and change the form. It's helpful if it displays at the top of the list of programs.

**Comment by clouser2** [comment]
Known issues are addressed. Now we want to get a little bit of Civiform Admin feedback on the new experience. Once this has been deployed to staging, I'll coordinate to make sure we gather feedback on the new UI.

For any interested, the new UI can be accessed from the typical `admin/programs` URL by appending the `v2=1` query parameter (e.g. https://staging.seattle.civiform.com/admin/programs?v2=1)

**Comment by clouser2** [comment]
We received positive feedback on the UI with no known blockers. Based on this, I'm going to proceed with making this the default view and deleting the old view.
