### ISSUE TITLE
Make Address question type's State input a dropdown

### ISSUE THREAD

**Issue by neel-a-mehta** [civiform/civiform#1485]
The Address question type currently uses a free-text-entry for the State field. The UX would be better (easier to use, harder to get wrong) if we instead used a dropdown.

![image](https://user-images.githubusercontent.com/77128518/123313821-b76af380-d4de-11eb-9647-302c9d689de4.png)

In the dropdown, offer all 50 US states, plus DC, PR, American Samoa, Guam, Northern Mariana Islands, and the Virgin Islands (56 in total).

We may want to style each dropdown item as `$Abbreviation - $State`, such as `WA - Washington` or `CA - California`. This would make the list easier to skim.

**Comment by elisekalstad** [comment]
Received this same recommendation from Seattle Parks and Recreation and the Age Friendly Programs. 

Problem Statement: Program Admins spend time cleaning up addresses because applicants can free-type different variations of "WA" "Washington" "Wa" and any misspellings. For programs that need to mail out a physical card or letter, program staff must first review and revise the addresses.

**Comment by elisekalstad** [comment]
[State selector.pdf](https://github.com/civiform/civiform/files/9933657/State.selector.pdf)

Just highlighting that it would be helpful to have a state selector with all 50 states plus territories, following the USPS guidelines: https://pe.usps.com/text/pub28/28apb.htm?_gl=1*ghw7cv*_ga*MTMxOTA1NjI3Ny4xNjY3NTE2NDky*_ga_3NXP3C8S9V*MTY2NzUxNjQ5Mi4xLjEuMTY2NzUxNzA5My4wLjAuMA..

**Comment by mferhut** [comment]
Hi @elisekalstad. I usually have seen either the name of the state written out or the state abbreviation vs showing both (ie WA - Washington). It may be harder to scan if we show both as users typically are looking for one of the two formats. I wanted to get your thoughts on this, would just showing the state name written out be ok? You mentioned the program admins will mail out letters, etc and exporting the address in one format may be easier to use when exporting out data. Thoughts?

**Comment by cassandralfernandes** [comment]
From a product perspective, it is best practice to choose either state abbreviation or the state name written out. Elise & Swathi - curious your thoughts. We can also add this as an agenda topic to our Seattle/CiviForm meeting later today if you'd like to discuss live.

**Comment by shanemc-goog** [comment]
We should also keep in mind what we want displayed and what we want stored/exported.

**Comment by elisekalstad** [comment]
Hi @cassandralfernandes  and @shanemc-goog. @swatkat1  is pretty far in development on this one. She is going to stick with the state abbreviation. The program staff told us that the full state name is difficult because can add extra lines on the address. 

![image](https://user-images.githubusercontent.com/86082659/200894375-0ab82bd7-33ec-471c-a488-17f49ccc2bab.png)

**Comment by elisekalstad** [comment]
@shanemc-goog -- that's my bad, I didn't see Neel's original request specified having the abbreviation AND the full state. I should have clarified. I recommend using the state abbreviation for both the dropdown display AND the exported value for program staff. It's easier for residents, especially if they are view civiform in a zoomed-in view. And for program staff, they specifically requested the abbreviation to make formatting addresses on envelopes easier.
