### ISSUE TITLE
Allow admins to rename questions once created

### ISSUE THREAD

**Issue by glorialiou** [civiform/civiform#1929]
This was feedback from both cities + the UX audit. Solution could be to allow editing of names for questions, but potentially there's a technical/eng reason we aren't allowing?

**Comment by baipai** [comment]
If I don't remember wrong and the system still follows the same.
This involves the whole ecosystem, not just the question part itself. 

Any changes in the question part will need the admin to push the "publish all programs"(it is under the program page) button in order to save the changes. This request did bring out during 2021 Q2 although I wasn't sure how it went in the end. But I know the engineer was looking into it.

**Comment by cassandralfernandes** [comment]
This issues is related to #3075 and the questions/program name meeting (meeting notes [here](https://docs.google.com/document/d/1peZ5tPhleq7Gdu7PoHJ_g9kUH9k5cBb9LXKMQYSvBcw/edit))

Proposed solution: 
On the questions page, remove the furthest left column that displays the admin question name
For questions, change the name of the description field to “admin notes”

**Comment by clouser2** [comment]
We've deephamsized the question name field throughout the UI and it's now referred to as "Admin ID". The primary text shown is the text associated with the question. @nbeloglazov updated the question list in #3033 and other parts of the UI were updated in #3075.

Since we didn't actually implement the title of allowing admins to rename questions, I'm going to close this as not planned.
