### ISSUE TITLE
Add screenshot diffing tests

### ISSUE THREAD

**Issue by jeanniefu** [civiform/civiform#2387]
We should look into setting up testing where screenshots are automatically taken and compared to previous screenshots. This can help us catch unintentional UI changes, and verify intentional ones.

**Comment by shanemc-goog** [comment]
Docs on taking screenshots are at https://docs.civiform.us/contributor-guide/developer-guide/testing#screenshots

**Comment by th174** [comment]
It looks like screenshot diffing requires the use of the Playwright Test runner. https://playwright.dev/docs/test-snapshots

We currently use the jest test runner, so we will have to migrate all of our test to playwright in order to take advantage of this feature. It looks like screenshot diffing is not supported with the jest test runner.

**Comment by th174** [comment]
As an alternative, we can work with jest's text based snapshots: https://jestjs.io/docs/snapshot-testing

This creates a JSON-like textual representation of the page, which can be diffed in the code review process. We won't have to migrate all of our tests if we do this, and we can still us the [existing screenshot capability](https://docs.civiform.us/contributor-guide/developer-guide/testing#screenshots) but we also won't have automated screenshot diffing.

**Comment by th174** [comment]
Another alternative would be to use a completely different library: https://github.com/americanexpress/jest-image-snapshot

I think we can use it, because it's under Apache License.

**Comment by shanemc-goog** [comment]
The American Express library looks really well rounded and easy to use in particular around adding and updating images.  I think the current thing we use for debugging stores them outside the code tree for instance where this will try to put them along side the test code. If it does "just work" that seems good to me.

@bion thoughts? and does the Apache 2 license look good for this?

**Comment by bion** [comment]
had a chat with @th174 out-of-band, let's go with the jest-image-snapshot lib

**Comment by th174** [comment]
The above pull request adds screenshot diffing checks to all of the browser tests. However, the tests fail currently because some screenshots don't match in the CI environment compared with the local environment it was generated in. I think this is because I was running `run-browser-tests-local`, since I cannot run `run-browser-tests` due to platform incompatibility issues.

I have an M1 Mac (arm64), while the browser tests can only run on linux/amd64 platform. It looks like the chromium distribution that runs inside the Playwright Docker container only runs for amd64. Honestly this makes a lot of sense Playwright is owned by Microsoft, so they obviously aren't prioritizing arm64 support.

**Comment by th174** [comment]
Since I can't debug the tests failures due to hardware compatibility, I'm going to unassign myself from this issue. Please feel free to pick it up.
