### ISSUE TITLE
Should "Review" and/or "Previous" save inputted info from that page?

### ISSUE THREAD

**Issue by glorialiou** [civiform/civiform#2470]
As we were playing around with the UXR prototypes, some of us found it surprising that clicking "Previous" from the first screen takes you back to the overview screen but with nothing saved. After playing around more, we noticed that clicking "Review" and "Previous" both don't save whatever info was filled in from that given page. We recognize that there is a "Save and Next" button, so it could follow that just that button does the saving, but we wanted to share that we were surprised by the not saving behavior.

We can discuss live in a meeting and specify what changes need to be made (or close this issue if none)!

**Comment by glorialiou** [comment]
Hi Raha, could you take a look at this issue? The decision we want to make is whether or not we should save inputted information when users click "Previous" and/or "Review," or to only save when they click "Save and Next." We can change the language of the buttons as well! Please ping me if you have any questions about this!

**Comment by clouser2** [comment]
If we decide to only save when the applicant clicks "Save and Next", we could pop a modal dialog/confirmation prompt when the other buttons were clicked, telling them that the info wouldn't be saved.

**Comment by rahaghas** [comment]
I think the ideal scenario would be that all changes to the application are automatically being saved on a rolling basis. Does this seem feasible? I have a mock of how we could be indicating that:
<img width="678" alt="Screen Shot 2022-05-18 at 11 58 12 AM" src="https://user-images.githubusercontent.com/103459221/169088323-5d366036-d093-4a3e-972d-05e614c45245.png">

This would sit at the top of every application whether you're on the review page or inputting information

**Comment by baipai** [comment]
For the long run, I agree with @rahaghas. But for the current situation, I know it will be a huge engineer's work. 

I think this question is also related to “review flow” and eligibility, and maybe it is better to consider the “process bar” all together to better make the whole flow/experience make sense. 

I assume there may be a few scenarios when users apply, the user login as a guest, the user login, and the final one, the user not login as a guest or login. But I know the final one isn’t happening now, so let's only consider the other two.


Here are some of my thoughts:

- When the button changes from “Next” to “Save and Next”, what does it mean for the users when they apply as a guest? It may let users think their information will be saved in the system. I am concerned it may not communicate in the way it is.
- If the purpose is to communicate “Next/Save and Next” button is the only button that can save the current filling moment. We can mention that at the beginning with eligibility info together before they start to apply the application and just like @clouser2 mentioned, do the modal confirmation prompt when they click “Previous”.
- For the “Review” button, I recall @shanemc-goog  brings that out in 2021 Q4 and there is the bug report(#1670) on it. I assume it may be hard to make the “Review” page saved due to some system constraint? if so, maybe its better to take out “Review” during the application and if possible put it in the final before the submission because users still need to final check the information. 
- For the eligibility part and progress bar part I will try to reply in the next few days.

**Comment by baipai** [comment]
And another thing I notice from the visual mock here, I am concerned the color and font size may not fit the **a11y** column. For the application part, the **a11y** should be the priority because of the user type and for the gov service it is dangerous not to follow the **a11y**. It may have some law issues. For **a11y**, I will try to reply to other github I’ve noticed in the next few days.

**Comment by rahaghas** [comment]
Got it. Thanks everyone. I think there's users expectation that "Next" and "Previous" will be actions that don't discard their work. However, when exiting an application process, emphasizing the fact that we will save their work thus far would be important. For this reason, my recommendation is:

**Save & Next** label changes to just **Next** (continues to save info)
**Previous** keeps its label (begins saving info)
Browser back and forward buttons work the same way as **Next** and **Previous**, saving info
**Review** label changes to **Save and review**, to emphasize that work will not be lost as they leave the application flow

Please correct me if I'm wrong but I believe that as long as cookies are not cleared, that a guest user's information can still be saved. Perhaps in this case, we should just warn them that clearing cookies will cause them to lose their information.

**Comment by shanemc-goog** [comment]
FWIW "Save & Next" was change to that from "Next" recently at the request of Seattle in #2098

**Comment by rahaghas** [comment]
Yes but based on this bug you've linked that was because it was the only way you could save your work, if all actions save work, I think "Next" and "Previous" will be working based on user expectations and the only one that would need the extra explanation would be "Review".

For browser back and forward, if that's going to discard work we should at least be popping up a warning then

**Comment by rahaghas** [comment]
fwiw, I believe most experiences still save information you input when you use browser back and forward

**Comment by rahaghas** [comment]
ideally browser refresh would also save work - since the ideal solution is that work is automatically saved, any action a user takes on this page would trigger a save as the interim solution

**Comment by shanemc-goog** [comment]
We should do more research on modern browser allowances I think, but In general I don't think browser controls are meant to double as web-app controls such that they will work reliably how we'd envision.  For instance, I don't think that we can handle form validation such that it would block the navigation.

It seems like modern sites/browsers have some ability to know if you might lose information by navigating or reloading and pop up a warning as such.  At least gMail in Chrome does.  That seems like a good approach to me.

**Comment by bion** [comment]
The main issue with attempting to save when the user does anything other than click a button clearly labeled "save" is what to do if the data they entered fails validation. IMO it's not a good experience for the user to click the back button and be shown validation errors instead of navigating to the previous page, for example.

**Comment by bion** [comment]
It's also pretty standard behavior across the internet to not save data the user has entered but not submitted when they use the browser's native UI to navigate.

**Comment by rahaghas** [comment]
So, I see saving what a user inputs as a different action from saving and validating. Only Next should save and validate, but Back, Review and any other action should just keep inputs filled.

**Comment by rahaghas** [comment]
As an example, if you try creating a Google account and use the back and forward arrows within the experience, the information stays filled in.

**Comment by rahaghas** [comment]
Ok well then we can not worry about the browser aspect, thanks for the clarification Shane. Just spoke to Bion a bit more about this and while it may also be a big lift, the ideal solution without having automatic saving would be:

Next - Keeps inputs filled & validates inputs (error messages appear below the question)
Previous - Keeps inputs filled 
Review - Keeps inputs filled & validates inputs (error messages appear to the right of the question on the review screen, where we would normally show the answer)

**Comment by shanemc-goog** [comment]
Currently we never save data to the database that has not been validated.  We always ensure the database data is valid.

What do you expect in the "Previous" situation around "Keeps inputs filled" where there is no validation?  If the user is on Page 4 of 7, enters an invalid income, clicks Previous, closes the tab.  When they come back later and see page 4 of 7 are you saying that should show the invalid income value?

**Comment by rahaghas** [comment]
Yes. the validation will occur the second they try to proceed to page 5 of 7 or Review their application. This will be especially useful to allow in situations where a specific screen has many questions and the user may want to leave and come back to it without losing half their work on that screen.

**Comment by rahaghas** [comment]
And if they click Review before finishing the screen, the page should be partially validated. If there are some errors we show them but we don't discard their inputs. They won't be able to submit the application until the errors are addressed

<img width="852" alt="Screen Shot 2022-05-27 at 10 57 28 AM" src="https://user-images.githubusercontent.com/103459221/170725192-1fb8d35c-fdf5-41f8-a654-652c31a4b567.png">
.

**Comment by shanemc-goog** [comment]
Ok, agree that it's a large lift given how CiviForm currently works.  If possible it'd be good to have an interim stage that doesn't require remembering values we don't persist into the validated application we store int the Database.

Also note, there's some difficult hurdles here around if the user has the application open in multiple tabs.


WRT to the Next/Previous naming.  Seattle had previously requested and implemented changing Next to "Next and Save" to reduce confusion, that was removed, so we may need to take that into consideration given the different operation model here.

**Comment by tinkelperson** [comment]
Reopening - can we consider removing the "review" button until we can implement an experience that saves data?

**Comment by caitlinshk** [comment]
The "Review" and "Previous" buttons now save data, or show an error modal if the data doesn't pass validation. See https://github.com/civiform/civiform/issues/6450. The change should be enabled in prod in the next few weeks.
