### ISSUE TITLE
Setup Bastion for AWS RDS

### ISSUE THREAD

**Issue by azizova-leyla** [civiform/civiform#2563]

**Comment by azizova-leyla** [comment]
Bastion is used to access database that's not publicly accessible.

**Comment by nbeloglazov** [comment]
Do you want to have an extra EC2 instance that always runs and that provides a way access RDS? And do you want to follow the pattern of how [azure](https://github.com/civiform/civiform/blob/main/cloud/azure/bin/db-connection) script is doing it? When admin wants to access DB this script modify security rules, adds a freshly generated SSH key, connects to the bastion EC2 instance and then removes SSH key upon end of the session?

**Comment by azizova-leyla** [comment]
That sounds reasonable.

**Comment by nbeloglazov** [comment]
Gave it more thought on Friday and now I have a slightly different proposal. Instead of creating EC2 instance that simply creates ssh tunnel and calls `psql` command line tool we start EC2 instance with pgadmin web app on it. Pgadmin starts with a randomly generated password that it printed when you run command-line script. Basically:

1. User runs `pg_access` script.
2. Scripts launches server using a docker image that contains pg admin on it. Pg admin is configured to access the database and also PG admin is using random password.
3. Script prints ip of the server and the password.
4. User opens pg admin in browser and works with DB.
5. User aborts the script. Script destroys server.

The dangers are:
1. Server needs to be available to the internet. Though to make use of it you need to know not only ip but also password. The password is printed only at step 3 so only user running the script knows it.
2. It's possible that user aborts script before server tear down logic had chance to run. In this case server can stay around for a while. Though password to access it will be lost so no one will be able to access pg admin. 

The benefits of using pg admin is that it provides more user-friendly interface. Which is important in this case given that users/admins who need to access civiform data might not be very familiar with the internal DB structure. And PG admin provides nicer UI for that kind of exploration. Plus it allows to run sql script from the page, similarly how they would run scripts using psql.

**Comment by avrittrohwer** [comment]
Got a proof-of-concept working of running pgAdmin as a fargate task.  Steps:

1. Create a new security group for the pgAdmin task.
   - Add an inbound rule to allow HTTP TCP traffic on port 80 from anywhere.
   - Add an outbound rule to allow all traffic.
2. Add a new inbound rule to the existing civiform_rds security group to allow PostgreSQL traffic from the newly created security group.
3. Add a new ECS fargate task definition with the dpage/pgadmin4:latest docker container.
4. Launch a new ESC fargate task with the new definition
   - Env variable overrides:
      - PGADMIN_DEFAULT_EMAIL=someemail@somedomain
      - PGADMIN_DEFAULT_PASSWORD=somepassword
   - Launch the task in the existing civiform VPC and the Civiform Public Subnet
5. Once the task is provisioned there will be a public IP in the AWS cli.  Click on the link, use the email and password to login.  Click on the 'Add server' link in pgAdmin, use the existing RDS DNS name, login username, and password (available in the Secret manager).

Things to figure out:

1. How to make connection to pgAdmin encrypted.

**Comment by avrittrohwer** [comment]
Public documentation of the pgadmin command: https://github.com/civiform/docs/pull/208
Additional pgadmin user-friendliness change: https://github.com/civiform/cloud-deploy-infra/pull/88

Feature is now in maintenance mode
