### ISSUE TITLE
Client information stores across sessions for TIs

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#2636]
**Describe the bug**
We heard from Trusted Intermediaries that they can submit an application for one client. But when they go to submit an application for a second client, the first client's information is pre-filled in the form.

**To Reproduce**
1. Login as a Trusted Intermediary
2. Add 1st client to client roster
3. Submit application for program for 1st client
4. Add 2nd client to client roster
5. Select application for 2nd client to apply to
6. See fields completed for 1st client

**Expected behavior**
TIs would start a new client with a "clean slate"--information from previous clients would not be populated. Perhaps a way to "wipe stored client information" between client sessions.

**Screenshots**
I unfortunately don't have screenshots, but will try to replicate the issue.

**Comment by bion** [comment]
Hi @elisekalstad have you been able to reproduce this issue? Do you know if it has affected more than the one TI?

**Comment by elisekalstad** [comment]
Hi @bion, I'm back in the "office" and can test it today. It is impacting all TIs.

**Comment by bion** [comment]
Thanks Elise, we'll get it fixed.

**Comment by bion** [comment]
@elisekalstad I dug around a bit more trying to reduce this behavior and was unable to. Would it be possible to schedule some time for me to observe a TI using the system so I can see them encounter it?

One thing to double check is that they have changed "identity" to work with the new client that they've added -- they *must* click the "Applicant dashboard" link next to the client's name in their client list to create an application for that client.

![image](https://user-images.githubusercontent.com/473671/173724313-38bdba7e-5e40-4fbe-9652-44ad7431dced.png)

If they create a new client in one tab, and navigate to the same program list page in the same tab they used for submitting the first application, they will still be viewing the system as the first client. At the top of every page for the TI when they're applying to programs there is a link to their dashboard and text telling them which client they're applying as. Double check they're aware of that and applying as the person they intend, instead of reapplying as their previous client and changing all their data.

![image](https://user-images.githubusercontent.com/473671/173724595-3478a227-5c04-4290-8d63-5afdc1053e14.png)

**Comment by bion** [comment]
My guess is that this a case of TI's getting confused with the UX, which means it's a good opportunity to improve the UX to make it less confusing. One more item for our big list of improvements @rahaghas

**Comment by bion** [comment]
@elisekalstad one more thing: I added a button on staging that allows you to sign in as a TI in demo mode. Feel free to use this to explore the behavior: https://staging.seattle.civiform.com/loginForm

**Comment by rahaghas** [comment]
I suggest an adjustment to the H1 here since "Get benefits" makes more sense for the Resident experience. Something like "Discover benefits for [Client name]", making it hard to miss which client's portal you're currently in.

**Comment by bion** [comment]
@elisekalstad it is possible, however one thing to note is that after a TI completes an application for an applicant they will still need to navigate back to the dashboard to select a different applicant unless they want to submit another application for the same applicant.

With that being said, does this capture the current request? "When I log into CiviForm as a TI, the first page I see is the TI Dashboard"

**Comment by bion** [comment]
@elisekalstad is this issue resolved?

**Comment by elisekalstad** [comment]
@bion  Yes!
