### ISSUE TITLE
Consider renaming the admin-facing "screen" concept to something more user-friendly

### ISSUE THREAD

**Issue by clouser2** [civiform/civiform#2668]
Here's to @kmcnellis for calling this out in #2660. Additionally, we could update admin-facing "Name" / "Description" language used for program / question editing to something more user-friendly, like "label" / "nickname".

@rahaghas - assigning this to you as it likely fits in with the work you're doing around revamping the Admin UI. Note that we could update the language independently of the UI if you have terms / concepts you'd like to use.

**Comment by rahaghas** [comment]
From speaking with Bion I believe "Screen" was chosen intentionally over "Page" due to the dynamic nature of the program experience, especially when enumerators are involved. My take personally is that the term "Page" can still be used even if more "Pages" get added based on user inputs, but adding Bion in case there are any strong concerns with this. @bion

**Comment by goldblatt** [comment]
Notes from priotization:
- from @bion there was an intentional choice to go with screen based on prior UX team due to the enumeration feature and thinking screens map 1:1 to 'pages.' 
- from @rahaghas we might want to remove the number of screens as well

overall: we are agreed that page makes more sense and we now have extra context that informed switching from screen to page! we will also need to update docs.civiform.ux (@rahaghas )
