### ISSUE TITLE
Make the set of available languages configurable via an environment variable

### ISSUE THREAD

**Issue by clouser2** [civiform/civiform#2800]
If a program wants to support a subset of our available languages, the `langs` value in `application.conf` can be set ([code](https://github.com/seattle-uat/civiform/blob/3f0f7228b56834e59104dacc43f12ea4a61bfa36/server/conf/application.conf#L196)).

We should make this overridable via an environment variable that's set through our deployment system, similar to time zone.

**Comment by clouser2** [comment]
Reopening so that we can ensure that the deployment system propagates this value and has configuration that allows the deployer to specify it (per the PR feedback on #2830).

**Comment by bion** [comment]
As per the last comment, the remaining piece here is to pass the variables through from the deployment system so they can easily be set by an IT admin.

The IT admin should be able to specify the language set in [civiform_config.sh](https://github.com/civiform/civiform-deploy/blob/main/civiform_config.example.sh) in their deployment-specific civiform-deploy repo and for those values to reach the CiviForm server.

This is made a bit tricky because the CiviForm I18n system consumes the config vars in the server, and requires that the languages be specified using a list [see full comment here](https://github.com/civiform/civiform/blob/main/server/conf/application.conf#L229-L257), which seems to require passing a separate env var for each item in the list. This could be tricky to make work with cloud deploy config loader: https://github.com/civiform/cloud-deploy-infra/blob/main/cloud/shared/bin/lib/config_loader.py

A possible approach to fixing this could be to specify the list as a comma-separated value in the civiform_config.sh file, parse it in python or terraform and then present the multiple env vars to the server in terraform.

**Comment by avrittrohwer** [comment]
This is the high-level flow of data from the civiform deploy config file to terraform code:

1. IT Admin clones https://github.com/civiform/civiform-deploy then copies the `civiform_config.example.sh` to `civiform_config.sh`.
1. IT Admin runs `bin/deploy --config=civiform_config.sh`. 
1. A bunch of bash and python code (that really needs to be simplified) runs.  To summarize a bunch of stuff, the `civiform_config.sh` is sourced so that all exported variables are in the bash and python's environment.  Then the code loops through every key defined in [cloud/shared/variable_definitions.json](https://github.com/civiform/cloud-deploy-infra/blob/main/cloud/shared/variable_definitions.json) and `cloud/<specific cloud provider>/templates/<specific terraform template>/variable_definitions.json` that has `"tfvar": true`.  If the key is defined in the environment, the key and value will be written to a .tfvars file.  We pass in the .tfvars file when calling terraform.  To use these variables in the terraform code we have to specify them in the `cloud/<specific cloud provider>/templates/<specific terraform template>/variables.tf file`.

For example, on AWS with the aws_oidc template, for the CIVIFORM_TIME_ZONE_ID config setting:

1. Set in the civiform_config.sh file: https://github.com/civiform/civiform-deploy/blob/main/civiform_config.example.sh#L134
2. Declared in the cloud/shared/variable_definitions.json file: https://github.com/civiform/cloud-deploy-infra/blob/main/cloud/shared/variable_definitions.json#L2
3. Declared in the cloud/aws/templates/aws_oidc/variables.tf file: https://github.com/civiform/cloud-deploy-infra/blob/main/cloud/aws/templates/aws_oidc/variables.tf#L25
4. Used in the terraform config to set a CIVIFORM_TIME_ZONE_ID environment variable for the civiform server: https://github.com/civiform/cloud-deploy-infra/blob/main/cloud/aws/templates/aws_oidc/app.tf#L87

**Comment by rockycodes** [comment]
Yep! You can set a subset of languages by setting `CIVIFORM_SUPPORTED_LANGUAGES` to a list of languages separated by a string in the deploy config.
