### ISSUE TITLE
Edit program questions middle pane too narrow

### ISSUE THREAD

**Issue by kmcnellis** [civiform/civiform#2808]
**Describe the bug**
When editing the questions, the middle tab (the list of question) is very narrow.  It only expands when you add a question with a long name or description. 

The question bank takes up most of the screen.

Instead, It should all be a fixed-width, regardless of what questions are added.

**To Reproduce**

1. Go to https://staging-azure.civiform.dev/admin/programs/52/blocks/1/edit
2. Add the question "Resident?" Notice the screen adjusts width
3. Add the question "UXR: How much local, state, or federal assistance (e.g. child care assistance) do you receive annually, if any?" Notice the screen adjusts width again

**Expected behavior**
The UI doesn't change widths between questions

**Screenshots**
1
![image](https://user-images.githubusercontent.com/5566205/176216431-ae308156-360b-49d9-9e1b-59b4ba25a4fc.png)

2 
![image](https://user-images.githubusercontent.com/5566205/176216365-853c128f-fb48-4288-985e-b64239c70bbb.png)

3
![image](https://user-images.githubusercontent.com/5566205/176216315-bfae3325-6e87-4fc5-89e4-2cc14b104c73.png)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Mac
- Browser [e.g. chrome, safari] Chrome

**Additional context**
The questions in the question bank have several very long titles.

**Comment by azizova-leyla** [comment]
the cause of the issue is the questions with very long titles. It breaks even worse if it doesn't have spaces once added to the screen, causing horizontal scroll. 
I'll fix the layout issues, but we should probably have some sane upper limit on question length. @cassandralfernandes wdyt?

![Image](https://user-images.githubusercontent.com/1741747/185255044-6f447718-ed8b-4a81-b895-e39689918e89.png)

**Comment by cassandralfernandes** [comment]
We also could truncate the question in this view with a "show more/show less" option. WDYT? 

Regarding question length limits, do you mean a limit on questing length for the admin name of a question (which is displayed in the screenshot, but we have talked about removing), or the question that is show to a user? 

A limit on admin name questions sounds fine. I'm hesitant to add a limit to the question that is shown to the user, since some programs paste their terms and conditions (which are long) into a check box or static question

**Comment by azizova-leyla** [comment]
Sounds good. I'll truncate it in the ui, and we can keep current limits.

**Comment by clouser2** [comment]
I'll look into this.

**Comment by clouser2** [comment]
I added some of my own sample questions and used a large screen resolution:
![Screen Shot 2022-09-01 at 11 50 32 AM](https://user-images.githubusercontent.com/1870301/187990543-66c452f2-899e-452c-a5b5-cb4a48d3906f.png)

A few things jump out:
  * On high resolutions, we're not allowing the content to grow. That seems unfortunate since this is a place where we'd clearly benefit from more real screen real estate. I'll look into adjusting that as well since we expect CiviForm admins to be operating on a desktop.
  * We're using flex sizing for both the question bank and program builder. Flex isn't great when the content can be super short or super long. We shouldn't adjust the size of each of these based on the question content.

I'll take a pass at those improvements. Additionally, I'll clip the question text / description text and put the remainder in a hover tooltip.

**Comment by clouser2** [comment]
Prototyped fixing the width of each element rather than allowing it to flex:
![Screen Shot 2022-09-01 at 12 14 23 PM](https://user-images.githubusercontent.com/1870301/187994390-5748d6e7-e420-45ce-9647-2ebde325c359.png)

In these cases, long questions end up wrapping vertically and not causing other elements to become cramped. We *could* add clipping in the UI, but I don't know that it's actually necessary given this. I'd be inclined to go with this and also allow the whole screen to take up all screen real estate.
