### ISSUE TITLE
Status Tracking: When a status is selected present confirmation dialog

### ISSUE THREAD

**Issue by shanemc-goog** [civiform/civiform#2912]
When the program admin selects a new status show the confirmation dialog.

**Comment by clouser2** [comment]
@shanemc-goog / @rahaghas 

Were there any mocks indicating what the confirmation dialog would say? I'm also happy to just propose text and address it in the PR review.

**Comment by clouser2** [comment]
Presumably, we want the behavior when the user cancels the confirm dialog to be to restore the previously selected status and do nothing. We likely also want the confirmation message to include the previous and to-be-set status as well.

Typically, we do all of this through a modal. However, modals have preset static content for the most part. We could do some tricks to adjust modal content. In this case, though, it feels like we might be able to get away with using the standard Javascript confirmation API. It's not as pretty as a modal, but we can dynamically build the content and it makes for a better flow for preventing updates. We have precedent for using this in the applicant-facing experience when removing an enumerated entity.

For expediency, I plan to start there and we can adjust if we think this is too divergent from the experience we want.

**Comment by shanemc-goog** [comment]
Mocks are [here](https://docs.google.com/presentation/d/12wEhWKPvPh-e3cdWAnL_NdT_I-YRnl1nYBTr9zes1vE/edit?resourcekey=0-x_YmnOany2v3hZr_fgLgJw#slide=id.gf43218f635_0_131)

**Comment by shanemc-goog** [comment]
I'm also recalling that Status and Notes are set differently, so will need a path for each, changing status is priority though.

**Comment by clouser2** [comment]
Thanks for the mocks. I think "Notes" aren't in scope for V1, correct?

**Comment by rahaghas** [comment]
I had it in the V1 mocks, but idk. @cassandralfernandes ?

**Comment by clouser2** [comment]
Regarding the confirmation modal shown. I'll scrap my idea from https://github.com/civiform/civiform/issues/2912#issuecomment-1217053343 since I'd forgotten that we wanted to allow triggering / not triggering the email.

We don't create dynamic modals throughout the codebase, so we'll need to come up with a solution. The simplest would be to create a modal for *each* status and show the correct one depending on the selection. That's a little bit wasteful but is also consistent with what we do elsewhere.

In an ideal world, we'd create a template for the modal with dynamically configurable attributes for each of the things that change (e.g. new status name, email configured, etc). Our current modal framework wouldn't really support this without additional custom JavaScript. That said, we'll need to add custom JavaScript anyway in order to pop the modal when the selection changes anyway.

Given that, I'm going to start by trying to develop the dynamic solution. If it becomes a timesink, I'll fallback on the modal-per-status approach.

**Comment by clouser2** [comment]
@rahaghas I may have just misunderstood.

One thing we're going to need to figure out is where to display the "list of previous statuses" and "list of notes" within the existing Program Admin UI. Do you have suggestions for that once @shanemc-goog 's data modeling change is available?

**Comment by rahaghas** [comment]
Can we treat rendering the historical info as a V2?

**Comment by clouser2** [comment]
That would work for me. In that case, the status selector would be the place we'd always show the current status, so there'd be no problem and we could tack on status history in V2.

In my opinion, if we didn't display the history for notes, there wouldn't be much use in having an "Add note" button in V1.

**Comment by rahaghas** [comment]
Why's that? Users can still keep a log of notes but just editing the note and keeping the previous string as part of it. But regardless I see value in being able to append a note.

**Comment by clouser2** [comment]
Gotcha. I'd forgotten about that. In the mocks I saw the dialog title being "Add a note" and extrapolated from there. We can use the "Edit note" trigger to show the existing note for now.

**Comment by rahaghas** [comment]
Sounds good!
