### ISSUE TITLE
Deploy scripts should work with release versions

### ISSUE THREAD

**Issue by azizova-leyla** [civiform/civiform#2926]
We want to support both SNAPSHOT and version tags.

**Comment by clouser2** [comment]
Sample SNAPSHOT-based tag: `SNAPSHOT-ce2974f-1658853033` ([DockerHub](https://hub.docker.com/layers/civiform/civiform/civiform/SNAPSHOT-ce2974f-1658853033/images/sha256-9a32f6190811c3f6f2adedf72181e38994cdbce2c08616eb77700e6f68e91ad9?context=explore)

Sample release tag: `v1.0.0` ([DockerHub](https://hub.docker.com/layers/civiform/civiform/civiform/v1.0.0/images/sha256-6c6b65d9278866ead276ff7eb3553931cc968ad0659a6ac645ba42d824b19ee3?context=explore))

These tags are applied as labels when building the Docker image.

Docker itself would allow us to specify the container image using either of the tags, but our deployment system has a few bits of additional validation and assumptions that a SNAPSHOT-based tag is being used:
  * In the main deployment code, we only ensure that the tag specified isn't `latest` ([code](https://github.com/civiform/civiform/blob/ce2974f3778489f6486bf52ff46c664410f2a309/cloud/shared/bin/deploy#L9-L12))
  * In the civiform-deploy repo, we have [helpers](https://github.com/civiform/civiform-deploy/blob/4b4e6cfceabf9ed301f0c15c0e14aae6e160433d/bin/lib/snapshots.sh) that parse the SNAPSHOT-based tag to extract the git commit hash. The reason for this is that we want to check out the "main" deployment repo's source at the same version as the tag that's being deployed (for consistency). This means that as-is, using a release tag would fail the following lines since there's no Git commit embedded in the tag ([code](https://github.com/civiform/civiform-deploy/blob/22e63047a3f993f1a6b695760094990422538bad/bin/lib/checkout.sh#L84-L93)).

In my opinion, it feels fairly prescriptive for the deployment scripts to enforce that a specific version type be deployed (either snapshot-based or release-based). Docker will run any tag specified so long as it resolves. I think it makes sense to *prefer* that these types of tags are deployed, but we could achieve that by:
  1) Validating that an image with the provided tag exists, whatever it may be
  2) Displaying a warning if that tag is something besides a version-based tag or a release-based tag.

Even if we did the above, we'd still run into the problem of needing to somehow retrieve the git commit hash from the specified image. In my opinion, the current approach is a bit more complicated than it needs to be. Using tags for embedding this type of information additionally has a downside of the fact that tags on an image are essentially mutable. This problem could be worked around by embedding the Git commit into the image itself through custom-metadata, which is immutable (https://docs.docker.com/config/labels-custom-metadata/). If we did this, then any code that was assuming a SNAPSHOT-based tag could instead just run a docker command to retrieve the Git commit. This would also work out of the box for release-based tags as well, since the underlying image would have the metadata.

The main downside of using labels is that we don't have them for old versions. That said, we also don't have active deployments using our system yet, so we could potentially introduce this ahead of time.

Concretely, my proposal is the following:
  * Add a `civiform.git.commit_sha` piece of metadata everytime we build an image (following instructions at https://docs.docker.com/config/labels-custom-metadata/)
  * Add validation at the beginning of deploy scripts that matches against a tag of either `SNAPSHOT-` or `vx.y.z`. If the tag doesn't match those, warn the user and allow them to continue if desired
  * Ensure the image can be found. This will save a costly debugging step later if Cloud infrastructure isn't able to resolve the image
  * Retrieve the `civiform.git.commit_sha` metadata from the image and use that instead of the current `snapshots::get_git_commit_sha` logic.
  * Remove the majority of the logic from the deploy repo that works with parsing snapshots

**Comment by clouser2** [comment]
Note: While the approach described might take a bit longer, I think it makes the system a bit more flexible and a bit less tightly coupled to tag formats.

**Comment by clouser2** [comment]
Indeed. I'll likely leave most of the logic in the repo, just reduce the amount of it / change what's validated.

**Comment by clouser2** [comment]
The first step is fairly straightforward, yay!

I added the following to the Dockerfile:
```
ARG git_commit_sha
LABEL civiform.git.commit_sha=$git_commit_sha
```

And the following to our `bin/build-prod` script:
  ```
  readonly GIT_SHA="$(git rev-parse HEAD)" # similar to what we do above for the SHORT_SHA
  # Other stuff
  docker build ...<other_args> \
    --build-arg "git_commit_sha=${GIT_SHA}" \
  ```

After running the script, I was then able to retrieve the value using the `docker inspect` command:
```
docker inspect --format='{{index .Config.Labels "civiform.git.commit_sha"}}' civiform
cb5703cea590deaa388784a84ee724971cb03723
```

**Comment by clouser2** [comment]
One potential wrinkle to the above is that we don't want deployers to have to have docker installed and pull the image in order to find this label. Fortunately, DockerHub has an API that can be used to extract metadata about the associated manifest.

I found the following article and was able to validate that I could extract the `civiform.git.commit_sha` label from the `latest` tag (https://medium.com/hackernoon/inspecting-docker-images-without-pulling-them-4de53d34a604).

I'll incorporate that into the script. We can additionally use this API to validate existence of the provided tag and fail-fast if it's invalid.

**Comment by clouser2** [comment]
Leaving manual verification that `civiform.git.commit_sha` is working here.

I first cleared all images on my machine, then executed the following:
```
docker pull civiform/civiform:latest
Digest: sha256:c59a6c13e23cfbbd89b92aef1134ad6bbe3436d38998dc235eda175ea0586a72
Status: Downloaded newer image for civiform/civiform:latest
docker.io/civiform/civiform:latest

docker inspect --format='{{.Config.Labels}}' civiform/civiform
map[civiform.git.commit_sha:772dfd74256a34b777af62ff2144e197790e7ed4]
```

**Comment by azizova-leyla** [comment]
fyi: we're already requiring docker cli to be installed: https://github.com/civiform/civiform/blob/main/cloud/shared/bin/doctor_impl#L17

**Comment by clouser2** [comment]
Fair enough. We should probably still avoid requiring an image to be pulled down for no reason since they can be hundreds of megabytes.

**Comment by azizova-leyla** [comment]
Agreed. Was just saying that using docker cli is totally fine.

**Comment by clouser2** [comment]
Paired with @bion on this. We rebuilt the existing v1.0.0 image to incorporate the changes from #2981.

We found the git commit by inspecting DockerHub:
![Screen Shot 2022-08-09 at 3 05 51 PM](https://user-images.githubusercontent.com/1870301/183774273-023ee814-7471-4662-90c5-31b68f107691.png)

The existing `v1.0.0` tag corresponds to the `SNAPSHOT-40c2c61-1658278166` tag (https://hub.docker.com/layers/civiform/civiform/civiform/SNAPSHOT-40c2c61-1658278166/images/sha256-6c6b65d9278866ead276ff7eb3553931cc968ad0659a6ac645ba42d824b19ee3?context=explore). The short commit SHA for this was `40c2c61`.

I did the following on my machine prior to running any steps:

```
# Clear all images and build cache
docker image rm -f $(docker image ls -q) && yes | docker image prune
yes | docker builder prune
```

Cloned a new repo at the specific commit:

```
mkdir civiform-temp
cd civiform-temp
git clone git@github.com:civiform/civiform.git
cd civiform
git checkout 40c2c61
```

We then hand-edited the bin/build-prod script to incorporate the changes from #2981 and updated it to not mark the image latest. For posterity, I pushed that to the repo as https://github.com/civiform/civiform/compare/clouser2/issue-2926-retag-v1. An important note is that the changes from the commit should be applied locally to the repo at the desired commit, otherwise the incorrect Git SHA will be embedded in the image.

We then built the image using the following:
```
# Note: PUSH_IMAGE=1 was specified in order to tag the versions, but all of the DockerHub logic was commented out.
PUSH_IMAGE=1 bin/build-prod
```

Ensured that the commit information was present:
```
docker inspect --format='{{index .Config.Labels "civiform.git.commit_sha"}}' civiform/civiform:v1.0.0
40c2c615fcd1c60c3813bdea16f671e9e1703621
```

Next, we pushed the created "SNAPSHOT" tag to DockerHub:

```
docker login
docker push civiform/civiform:SNAPSHOT-40c2c615-1660163636
```

This worked and is available on Docker Hub: https://hub.docker.com/layers/civiform/civiform/civiform/SNAPSHOT-40c2c615-1660163636/images/sha256-02c0f69be436c0eaf2ea64298dc1568c375e988cbb03d5cd68cd155201999637?context=explore

I'll confirm with @bion and then push the `v1.0.0` tag.

**Comment by clouser2** [comment]
Confirmed and ran `docker push civiform/civiform:v1.0.0`, which shows up successfully in DockerHub: https://hub.docker.com/layers/civiform/civiform/civiform/v1.0.0/images/sha256-02c0f69be436c0eaf2ea64298dc1568c375e988cbb03d5cd68cd155201999637?context=explore

This can now be considered complete.
