### ISSUE TITLE
CiviForm admin UX: Add "create new question" button to the question bank 

### ISSUE THREAD

**Issue by cassandralfernandes** [civiform/civiform#3032]
**Is your feature request related to a problem? Please describe.**
It is not clear to the user how navigate from the program page to create a new question

**Describe the solution you'd like**
Add "create new question" button to the question bank that takes the user to the questions tab 

**Additional context**
From admin UXR feedback sheet 
We need to confirm whether the button would take the user to a new tab or remain in the same tab

**Screenshot*
<img width="1533" alt="Screen Shot 2022-08-02 at 4 07 45 PM" src="https://user-images.githubusercontent.com/99513234/182489744-fc17a6f0-c396-4f60-ab54-1b68b16b796c.png">

**mocks**
https://docs.google.com/presentation/d/15fcq3dYFgy1Dfy2UjZybmHD9KIW5cz8Q1BjwgOpLJ7g/edit#slide=id.g13ec4604693_0_91

**Comment by clouser2** [comment]
The question bank doesn't dynamically refresh if a new question is added. Given this, if we opened "Add question" in a new tab, the admin wouldn't see the new contents until the previous tab was refreshed.

@rahaghas Given this, does it make sense to start by opening it in the same tab?

**Comment by rahaghas** [comment]
Yes, what I would love if we could do for this one is have a version of the question tab that hides all the tabs at the top and just includes an "x" in the corner that takes you back to the program you were just editing. How difficult would this be? Including a mock:
<img width="742" alt="Screen Shot 2022-08-22 at 1 07 45 PM" src="https://user-images.githubusercontent.com/103459221/185979177-0d37ac41-2210-4141-91c4-d21182b9e7ce.png">

**Comment by clouser2** [comment]
Credit goes to @nbeloglazov for suggesting an experience where the "source" of showing the "Create question" page is persisted. @rahaghas and I discussed and think it would make sense to do the following:

**Program builder page**
* Add a "Create new question" button in the question bank with the existing dropdown behavior
* Once a selection type is created, the same tab is navigated to the existing "New checkbox question" UI

**New question UI**
* Upon successfully creating the question, navigate back to the program builder page rather than the questions list page
* Add a "Cancel" button at the bottom of the form that also navigates back to the program builder page.

A couple of edge cases to be wary of:
  * If there were form errors, we re-render the create question page. We'll want to ensure that the destination continues to be persisted even in the face of that type of problem.

**Comment by rahaghas** [comment]
Thank you @nbeloglazov and @clouser2 !! way better solution :)

**Comment by cassandralfernandes** [comment]
I love the solution of having a "Create new question" button in the question bank and moving through the UI flows you outlined -- that's really great. 

This is obvious, but just want to confirm that all changes a CiviForm admin has made to their program are saved when the user is taken to the "new question" UI?

**Comment by clouser2** [comment]
> This is obvious, but just want to confirm that all changes a CiviForm admin has made to their program are saved when the user is taken to the "new question" UI?

Great callout! Changes will be persisted in all cases except the following:
  * The "Edit screen name and description" button is clicked
  * A new value is entered and save is not pressed
  * User clicks the "X" in the modal to close it

In this case, the pending changes won't be persisted. This scenario would however also occur for all of the other state mutating actions one could take from this page (e.g. adding from the question bank, deleting a question from a screen, switching to a new screen, adding a visibility condition). As such, I think we're ok here.

**Comment by clouser2** [comment]
Both parts of the proposal have now been fixed. Closing this out!
