### ISSUE TITLE
CiviForm admin UX: Consolidate "admin name and description" and "name and description visible to applicants" 

### ISSUE THREAD

**Issue by cassandralfernandes** [civiform/civiform#3075]
**Is your feature request related to a problem? Please describe.**
The CiviForm admin does not see a need for "admin name and description" and "name and description visible to applicants" to exist separately. From the user "Admin name field is really confusing and not necessary. It’s not clear that the notes field is text for admin only."

**Describe the solution you'd like**
Consolidate "admin name and description" and "name and description visible to applicants" and only one field called "admin notes" 

With this change, the public facing question name should become the searchable name in the question bank 

**Additional context**
From admin UXR feedback sheet

**screenshots**
<img width="1550" alt="Screen Shot 2022-08-05 at 2 14 11 PM" src="https://user-images.githubusercontent.com/99513234/183196754-bf84effa-a2e1-4b22-ab9e-5aac7677b4cb.png">

[mock here](https://docs.google.com/presentation/d/15fcq3dYFgy1Dfy2UjZybmHD9KIW5cz8Q1BjwgOpLJ7g/edit#slide=id.g13ec4604693_0_105)

**Comment by clouser2** [comment]
Our internal / external identifiers for programs and questions are baked pretty far into the system. This change unfortunately won't be straightforward since we require the internal name to not change over the course of question or program. Using the external value in the program / question UI could lead to confusion since the external name can change over time. Additionally, if there's both an active version and a draft version (each with different values for the display name), it will become difficult to choose what to show.

This one still needs a fair amount of scoping on the eng side. Perhaps a small approach might be to better group the fields like we do for program creation/editing.

**Comment by cassandralfernandes** [comment]
After meeting with Brett, Leyla, Shane, Bion, and Raha (notes [here](https://docs.google.com/document/d/1peZ5tPhleq7Gdu7PoHJ_g9kUH9k5cBb9LXKMQYSvBcw/edit)) , the proposed approach is as follows: 

- For programs, change the way the name field is described to "Craft your program's permanent URL. This will end up looking like <insert example URL> to the applicant". No data cleanup right now. Gray out the field so it's more clear to users that they cannot edit it 
- On the questions page, remove the furthest left column that displays the admin question name
- For questions, change the name of the description field to “admin notes” 

Remind me where we landed for the internal name field for questions? @rahaghas @clouser2

**Comment by cassandralfernandes** [comment]
Related to #3076

**Comment by clouser2** [comment]
We're addressing the internal name/description issues in #3085. For questions, we indeed need to keep the internal identifier for the question since it's used as the identifier to link different versions of question together across versions. As such, we'll need to continue requiring this field to be provided.

As part of the work @nbeloglazov did in #3033, we now display the internal name/description in the question list in the "Admin note" section, which hopefully has deephamsized it sufficiently.

We can continue this stream by also:
  * Moving the "internal" fields in the question builder below the "external" fields
  * Renaming "Description" to "Program note for administrative use only"
  * Changing "Administrative name" to "Administrative ID. This value cannot be changed later" (similar to what we did in the program builder)
  * Stop showing a disabled input for the administrative name when in the edit view for a question. Instead, render a static element with the value, similar to what we did for the program URL in the program builder

This approach will hopefully also allow us to close out https://github.com/civiform/civiform/issues/1929#issuecomment-1215902684.

**Comment by clouser2** [comment]
Independently, I'll also address @cassandralfernandes 's suggestion to use the external-facing question text in the question bank.

**Comment by clouser2** [comment]
The field reordering is complete. The work that remains is to update the text shown in the question bank to reflect the external-facing description of the question. While looking into this, I noticed we'll also want to do this on:
  * Program builder list of questions on a screen
  * Visibility conditions page
  * Visibility condition description. Currently it displays a String that's cobbled together based on the internal question name.

There will also be a host of browser test changes needed for this, since we manipulate questions quite a bit.

Since we're currently showing the internal name on each of these pages, I'll try and split them into separate PRs to minimize the churn.

Finally, we'll need a way to disambiguate two questions which have the same external display text. For this, @rahaghas mentioned that we could add a third line to the question bank and other places that has internal ID listed.

**Comment by clouser2** [comment]
This workstream is complete. All references to question text known to me have been updated.
