### ISSUE TITLE
CiviForm admin UX: Allow user to edit the internal program name 

### ISSUE THREAD

**Issue by cassandralfernandes** [civiform/civiform#3085]
**Is your feature request related to a problem? Please describe.**
CiviForm admin cannot edit internal program name 

**Describe the solution you'd like**
Allow CiviForm admin to edit the internal program name 

**Additional context**
<img width="1433" alt="Screen Shot 2022-08-05 at 3 15 17 PM" src="https://user-images.githubusercontent.com/99513234/183218367-0cbf37d7-d044-4d54-b736-a16c3c285a02.png">

**Comment by cassandralfernandes** [comment]
This issue is related to #3075 

In the current experience, users already are able to edit the admin description. So we're just talking about the internal program name in this issue

Instead of allowing the user to edit the internal program name, change the way the name field is described to "Craft your program's permanent URL. This will end up looking like (insert example URL) to the applicant". Gray out the field so it's more clear to users that they cannot edit it

**Comment by clouser2** [comment]
Starting to look into this. One thing to note is that we presently show the internal name / description of a program on the program card in the index view (for both program admins as well as CiviForm admins):

![Screen Shot 2022-09-13 at 3 12 39 PM](https://user-images.githubusercontent.com/1870301/190018628-c503252e-4f51-4ed3-ac50-61ec79f40e3a.png)

This is the logical sequence I'm planning to implement in, with the idea that each builds a bit of value:

1. **Update the program list to display the EXTERNAL-facing program name and description on the card.**

Since we're thinking of renaming the INTERNAL-facing description to "internal admin note", I think we'd still want to show it here as well (if present). We could likely show the EXTERNAL-facing description directly below the EXTERNAL-facing name and then put the INTERNAL-facing description at the bottom of the card (like it is now).

One edge case we'll need to account for is if there's a draft program that has edited any of these fields. That said, we could probably just break the tie and use the draft version's data, since it's what would be published anyway.

By default, we sort the list of programs by most recently modified. The database value to populate this was added relatively recently and we have a secondary sort in place for older entries that don't have a last updated timestamp. Presently, those are sorting based on the INTERNAL-facing name. We should update them to sort on the EXTERNAL-facing name, since that's what's now displayed on the program card.

2. **Reorder / rename the fields in the program creation / editing UX**

Current field ordering / names:
![Screen Shot 2022-09-13 at 3 18 15 PM](https://user-images.githubusercontent.com/1870301/190019287-46915ef8-a0a4-4a6e-8dbb-2d669de609b0.png)

We can move all of the "Visible to applicants" fields to the top. We'll then move the INTERNAL-description field to the very bottom and attempt a rendering similar to the mocks in https://github.com/civiform/civiform/issues/3075#issuecomment-1215439131. Finally, the INTERNAL-name field will better reflect it's readonly nature in the editing view.

We can also render the value as the slugified link that will actually be used rather than the freeform text that we previously allowed. This will be consistent with what would happen if the admin clicked "Copy link" on the program card.

3. **Enforce newly created programs enter a valid slug**

Since we were previously displaying the INTERNAL-facing program name in the UI, we had a need to allow semi-arbitrary text. After the above steps, that'll no longer be the case and we can start requiring new programs to explicitly fit into the slugified format (e.g. all lowercase characters, numbers, and hyphens). This will hopefully lead to fewer surprises when choosing or crafting the URL.

I'll start on the first step tomorrow.
