### ISSUE TITLE
Fix text bolding in browser screenshot tests

### ISSUE THREAD

**Issue by jeanniefu** [civiform/civiform#3225]
When running browser tests with our default command (bin/run-browser-tests), the screenshots that are taken do not appear to show bolded text. We should investigate why this is, and fix it so that the screenshots are more representative of what is shown in prod.

From some initial investigation:
* We currently use Chromium for our browser tests. If we use e.g. webkit or firefox, then the bolding works.
* When we run the test locally (e.g. not through docker), the bolding also works.

One hypothesis: 
* I believe we are using the default font, which is specified by a combination of OS and browser. Perhaps when running through docker, we use a stripped down version of fonts where the bolded versions are not included (?). We could try specifying our own default font that CiviForm should use (should check with UX).

**Comment by avaleske** [comment]
Running it in docker, but with a serif font, works:
![image](https://user-images.githubusercontent.com/1295824/214975279-5b84b0ae-2399-47cb-ab61-28137d637e88.png)

But with the default sans-serif font, it doesn't:
![image](https://user-images.githubusercontent.com/1295824/214975451-7ca2ae1c-367c-453b-9901-1ab8c426bfee.png)

**Comment by avaleske** [comment]
And it is a font issue. If I set the font-family to `['Arial', 'san-serif']` then it works

![image](https://user-images.githubusercontent.com/1295824/214979644-35790b03-57ed-446f-94fc-db1a51ab7d60.png)

**Comment by avaleske** [comment]
digging in a little more deeply:

`ui-sans-serif`:
![image](https://user-images.githubusercontent.com/1295824/215202161-0dade889-2b68-47bc-b576-2b21c50a247c.png)

`system-ui`:
![image](https://user-images.githubusercontent.com/1295824/215201257-c785f540-44e8-43ce-9974-6e1137315756.png)

`sans-serif`:
![image](https://user-images.githubusercontent.com/1295824/215202441-f33da5ca-2266-4bfd-a381-bf5fe206cd6b.png)

So the system fonts don't work, but the browser font does.

One fix is to just set the default font to `sans-serif`, which would result in using the browsers default sans-serif font instead of the OS's font.

**Comment by avaleske** [comment]
The fix for this is to add a fonts.conf to the docker container to override the default font that `fc-match` is picking for the `system-ui` generic font family.

## The issue
Tailwind uses a system font stack, outlined [here](https://tailwindcss.com/docs/font-family). There are a lot of benefits to this! It's fast, system fonts look good, and there's less for the user to download. The site also looks more integrated with the user's device.

The css tailwind generates looks like
```
font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
```

This defaults to the font the user's OS picks, with some OS specific fonts called out explicitly. More details are at https://woorkup.com/system-font/, but TLDR is that `system-ui` is a generic font family that tells Chromium to ask the system a sans-serif font. On macOS, that is San Francisco, on Windows, that's Segoe UI, on Android it's Roboto, etc.

On Ubuntu it _should be_ Ubuntu, but our browser-test docker container is missing a lot of things to keep it light. Confusingly, however, Ubuntu is installed, but it's not the font that gets picked as the font to use for the `system-ui` generic font family.

## Troubleshooting
We can see the font that gets picked using `fc-match` in the docker container. In this case, `$ fc-match system-ui`. This returns 
```
$ fc-match system-ui:bold
wqy-zenhei.ttc: "WenQuanYi Zen Hei" "Regular"
```
which is an open source font for Chinese that doesn't have any bold variations for latin characters.
<img src="https://user-images.githubusercontent.com/1295824/216388910-ff7b538c-2b17-4026-8653-194aae64c139.png">

To fix this, we can override the font that `fc-match` picks by adding a `fonts.conf` to `/root/.config/fontconfig/`, which we'll do by symlinking it from the browser-tests folder. That file lets us set a preference for what font to pick for a requested font family, using the steps from https://jichu4n.com/posts/how-to-set-default-fonts-and-font-aliases-on-linux/.

## After setting this fonts.conf:
```shell
$ fc-match system-ui:bold
Ubuntu-B.ttf: "Ubuntu" "Bold"
```
![Ubuntu](https://user-images.githubusercontent.com/1295824/216390125-b0fd9427-63a8-46eb-8866-16631d93527d.png)

We also tried Liberation Sans, and just removing the `system-ui` generic font family from the css font stack, but Ubuntu looked the best and had the best variation between bolds, which ideal for screenshot tests.

## Other things we tried
We tried setting a locale in the docker container, since a locale wasn't set. https://bugs.chromium.org/p/chromium/issues/detail?id=1247383 indicated that maybe `fc-match` was picking WenQuanYi Zen Hei because it is the best match when a locale isn't set. We did this by adding the following to playwright.Dockerfile:
```
RUN apt-get clean && apt-get update && apt-get install -y --no-install-recommends \
    locales
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
```
but it didn't work.

We also tried to get an x session in the docker container, so we could open an interactive chromium window and use the dev tools to see exactly which font was picked. We tried following the steps from https://www.howtogeek.com/devops/how-to-run-gui-applications-in-a-docker-container/, https://github.com/microsoft/playwright/issues/14250, and. setting playwright to headed mode, and setting the following in the dockerfile
```
RUN apt-get update && apt-get install -y --no-install-recommends \
    dbus-x11 \
    libexo-1-0 \
    x11-apps \
    x11-xserver-utils \
    xauth \
    xfce4 \
    xfce4-terminal \
    xterm \
    fluxbox \
    xinit \
    xterm \
    xorg \
    openbox
```
but we couldn't get an startx to start saying `parse_vt_settings: Cannot open /dev/tty0 (No such file or directory)`

Trying to start chromium with `/ms-playwright/chromium-1045/chrome-linux/chrome --no-sandbox` would error saying it couldn't find an x server.

We also tried removing the font, with `apt-get remove fonts-wqy-zenhei`, but that results in `fc-match` picking Loma, a font that doesn't have as clear a difference between the light and bold variants.

**Comment by avaleske** [comment]
We tried to push a fix for this, but ran into issues getting presubmits to pass.

Initially we pushed it all as one PR, with the changes to the dockerfile and the new goldens in one PR, but the presubmits were failing.

The presubmits re-generate the docker image though, so this error is confusing. And we added a debug line to `civiform-browser-tests/bin/wait_for_server_start_and_run_tests.sh` to print the output of `fc-match system-ui:bold` and it prints `Ubuntu-B.ttf: "Ubuntu" "Bold"`, as expected.

So we thought maybe there was some sync issue and it was generating a new image but then still pulling an outdated one from dockerhub, so we tried submitting just the change to change the dockerfile as #4155, which worked, and then submitting the change to the goldens as #4239, which did not. The presubmits are still taking screenshots of pages that don't have bold fonts.

So we're reverting #4155 for now and we'll try and figure out what's wrong with the presubmits later.
