### ISSUE TITLE
Status Tracking: Allow filters for the Application list

### ISSUE THREAD

**Issue by shanemc-goog** [civiform/civiform#3269]
The entire Application List view is being revamped so we'll need to do a low-waste take at it in the current UI.

A MVP should allow for a filter selector showing
- all options available in the Applications that could be listed
- An option to show those with no status that can have a status selected.

Note: For applications on programs without statuses there is no status option available.

**Comment by clouser2** [comment]
@rahaghas I was thinking for the V1, we could add the filter below the search box and before the Download / Filter buttons:
![Screen Shot 2022-08-25 at 11 29 00 AM](https://user-images.githubusercontent.com/1870301/186741583-818de1c8-11a0-46f9-b967-9c1bfdef6d8b.png)

I think the ideal experience would be a multi-select control of some sort. That said, I feel like checkboxes could take up a lot screen real estate. Additionally, we don't have any sort of dropdown-containing-checkboxes control that we can reuse. Building that would likely be a large amount of effort.

If we don't expect a need to choose more than one status when filtering, our V1 could simply be a select with a dropdown of the options.

What do you think?

**Comment by clouser2** [comment]
As part of this work, an interesting challenge around our data modeling and applying it to filters emerged.

## Background

**Status change modeling** - Presently, any time the status is changed, an `ApplicationEvent` with a type of `status_change` ([code](https://github.com/civiform/civiform/blob/4f0821e44f89b43ee9a0ab86a75b29faabfd83e2/server/app/models/ApplicationEvent.java)) is added. As such, there are many `ApplicationEvent` entities associated with a given `Application`.

**Application filtering requirements** - Presently, we filter the set of applications shown to the program admin entirely in SQL ([code](https://github.com/civiform/civiform/blob/4f0821e44f89b43ee9a0ab86a75b29faabfd83e2/server/app/repository/ProgramRepository.java#L227)) since there can conceivably be O(thousands) of applications. Due to this (per @bion), the decision was made to do filtering at the database level rather than the application level since it would be more performant and consume less memory.

## Problem

Filtering based on application status given the current model would require joining the filtered set of applications with a query that:
  * Retrieves all `ApplicationEvent`s corresponding to a status change
  * Groups by application id and only retrieves the latest value

Expressing this in SQL may be possible, but very likely won't be performant since the cardinality of the right side of the join will consist of all application events for all applications. The belief is that the query planner would likely end up just doing N subqueries for all events corresponding to the filtered set of applications.

Additionally, any time we want to show the current status in the UI (e.g. #3267), we'll need to do a subquery to retrieve and perform the same filtering to retrieve the status.

## Potential solutions

A common approach to problems of this type is denormalization, wherein a `latest_status` column is added to the `Application` table. This would logically correspond to the value from the latest `ApplicationEvent` of type status_change.

With respect to querying, this approach would be much more performant since we'd be adding another `OR latest_status = {filter_value}` clause to the existing filters. For UI that wants to show the current status, we can avoid the need for a subquery as well.

The main challenge with this approach would be ensuring that the `latest_status` column accurately corresponds to the latest `ApplicationEvent` with type `status_change`. A failure to update this column would be an area for errors and maintainability drain. A few alternatives are outlined below.

### Maintain this relationship in application code

This approach would ensure that anytime we write / update an `ApplicationEvent` record, the corresponding `Application.latest_status` column would be updated as well. Additionally, we would want to prevent `Application.latest_status` from being updated by application code. This is achievable, but will be pretty easy for bugs to emerge over time if this constraint isn't properly enforced. As far as I can tell, Play framework doesn't provide any primitives for this type of thing.

### Add a virtual column (enforced in DB)

A virtual column is one that is generated based on other values within the database. This has the nice properties of being a readonly column that application code wouldn't really be able to modify. Within Postgres, virtual columns are supported but can't reference other tables ([docs](https://www.postgresql.org/docs/current/ddl-generated-columns.html)). Since we'd want the virtual column to exist on the `Application` table and reference values from the `ApplicationEvent` table, this is a non-starter.

### Add a materialized view (enforced in DB)

A materialized view is a table whose values are precomputed and allow for more efficient querying of values that would otherwise be expensive to compute ([docs](https://www.postgresql.org/docs/current/rules-materializedviews.html)). With a materialized view, we could build an intermediary table that could be used to map application IDs to the latest `ApplicationEvent` entry with type `status_change`. This could then be used in a join in our query.

Materialized views need to be manually updated and regenerate the entire table as I understand. We would essentially need to regenerate this any time an `ApplicationEvent` is added/updated, which seems like it could be pretty expensive.

### Add a database trigger (enforced in DB)

Database triggers are well-supported in many database implementations, including Postgres ([docs](https://www.postgresql.org/docs/current/sql-createtrigger.html)). Triggers can be created which execute SQL whenever a row within a table is inserted/updated/deleted. Additionally, a trigger can be "triggered" based on an entry in one table and execute a function that updates an entry in another table.

Triggers are less preferable to virtual columns in that a trigger executes arbitrary code and we can't have the nice "readonly" property for the `Application.latest_status` column. However, we can add triggers both on `Application` and `ApplicationEvent` entities being inserted/updated to ensure that this type of consistency is provided.

The main downside to using database triggers is action at a distance and discoverability.

## Proposed solution

I propose starting with a solution that uses a database trigger since it allows us to maintain the desired invariant at the database level and seems like the best fit of the database-level mechanisms described above.

The downside of action at a distance / discoverability is real. This can hopefully be mitigated by pointing directly to the code corresponding to the database trigger within the javadoc for the `Application.getLatestStatus` method to be added. Additionally, the proper function of this can be asserted through unit tests.

Should we go a different route in the future, we're not tied in to this solution.

**Comment by clouser2** [comment]
There's still an open TODO against this that I need to complete. The majority of the work here is finished. The only remaining item is a bit of polish on the grouping of options within the dropdown.
