### ISSUE TITLE
Enable HAR files collection in browser tests

### ISSUE THREAD

**Issue by nbeloglazov** [civiform/civiform#3319]
Along with videos, playwright can save HAR files that contains HTTP traffic. This will be useful for debugging tests, especially given how traffic-intensive (many requests) is civiform. See `recordHar` option in https://playwright.dev/docs/api/class-browser#browser-new-context

**Comment by clouser2** [comment]
This definitely could be quite appealing. One thing to be wary of is that HAR recording will capture ALL of the network traffic, including session cookies etc. For these purposes, this might include the ID token as returned by Auth0, along with any cookies from any entity's auth provider.

For our staging environments and current places we run tests/probers from, this may be relatively benign. However, if we were to run this against a real production auth provider, it could be more problematic. Additionally, things like the test user's name and password would end up showing up in the HAR, which we currently keep in GitHub secrets.

I'm not trying to say this wouldn't be useful, just trying to say we might want to be extremely careful about when to enable this due to the verbosity of information contained.

**Comment by nbeloglazov** [comment]
Makes sense. I think we'd enable it only in browser tests running on local environment (github actions). As for name/passwords. Hm, do we have those in browser tests? I expected them to be in plain text in test code anyway given that it's test.  But I guess if you are adding login tests that should work on staging - then name/password should be in GitHub secrets as you said?

**Comment by clouser2** [comment]
Agreed regarding only running on local environments and not GitHub actions. Given the potential downside of accidentally running in CI, I'd go a step further and have the code that enables HAR recording throw an error if any of the default GitHub runner environment variables are set (e.g. CI, GITHUB_*, [GitHub docs](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables)).

Regarding names and passwords: Presently, Seattle staging probers have a test user / password that's passed as a GitHub secret. As such, it's not stored in plaintext anywhere in the source. However, if HARs are enabled, the network request would be sent with the name password in the POST body and hence be recorded. Note that we'll be adding another account of this type for AWS staging probers as well.

**Comment by gwendolyngoetz** [comment]
The playwright trace files provide significantly more information and is our current default now.
