### ISSUE TITLE
PDF export should include link to any uploaded documents

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#3351]
**Is your feature request related to a problem? Please describe.**
Program admins find it simple and useful to view the submitted applications via the new PDF export. However, they cannot view any uploaded documents via the PDF export. It would be helpful if the PDF export included a link to any uploaded documents. It would be easiest if they could click on the link and have the document automatically download OR open in a new browser tab.

**Describe the solution you'd like**
Include the URL for the residents' uploaded documents in the PDF export. It would be helpful it the Program Admin could click directly on the URL to download the document OR open in a new browser tab.

**Additional context**
Idea attached

**Done when**
Program admins can open residents' uploaded documents from the PDF export
[PDF with URLs.pdf](https://github.com/civiform/civiform/files/9499846/PDF.with.URLs.pdf)

**Comment by gwendolyngoetz** [comment]
I was discussing this on Slack with other engineers. As an extra layer of defense, if the file extension isn't on the allowed list of file types we want to display a warning message instead of a link to the file itself. That way folks can't accidentally click on something like an executable.

Rough language, but get something to better wordsmith this:

"Warning: "%filename%" has an invalid extension. Please contact CiviForm Support to assistance. %whatever ids we have to allow support to track down and inspect the file%"

**Comment by swatkat1** [comment]
We already have a allowed list of files and I don't see any reason why we should enforce the download here. This will be the same as clicking the "Click to download" as we have in view applications page. Instead of reactive Civiform app, it will be a offline download.
