### ISSUE TITLE
Use docker-based cli for AWS

### ISSUE THREAD

**Issue by azizova-leyla** [civiform/civiform#3508]
- [ ] Add GH Action test with USE_DOCKER-true https://github.com/civiform/cloud-deploy-infra/blob/main/.github/workflows/aws-oidc-deploy-test.yaml
- [ ] Make sure it will work from https://github.com/civiform/civiform-staging-deploy/blob/main/.github/workflows/aws_deploy.yaml
- [ ] Switch the scripts in https://github.com/civiform/civiform-deploy and https://github.com/civiform/civiform-staging-deploy to use docker by default

**Comment by avrittrohwer** [comment]
Will need to update the current [deployment docker file](https://github.com/civiform/cloud-deploy-infra/blob/main/cloud/cloud.Dockerfile).  When running the setup command on amd64 the container fails with:

```
  File "/cloud/aws/templates/aws_oidc/bin/aws_cli.py", line 31, in get_current_user
    res = self._call_cli('sts get-caller-identity')
...
FileNotFoundError: [Errno 2] No such file or directory: 'aws'
```

The `No such file or directoy: 'aws'` error, in this case at least, really means that the aws executable is dynamically linked against libraries that are not present on the host.  I changed the [docker compose file](https://github.com/civiform/civiform-deploy/blob/main/bin/lib/docker-compose.yaml#L21) command to `bash` to give me a shell in the container:

```
bash-5.1# ldd $(which aws)
        /lib64/ld-linux-x86-64.so.2 (0x7f843b354000)
        libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f843b354000)
        libz.so.1 => /lib/libz.so.1 (0x7f843b33a000)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f843b354000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f843b354000)
Error relocating /usr/local/bin/aws: __strcat_chk: symbol not found
Error relocating /usr/local/bin/aws: __snprintf_chk: symbol not found
Error relocating /usr/local/bin/aws: __vfprintf_chk: symbol not found
Error relocating /usr/local/bin/aws: __realpath_chk: symbol not found
Error relocating /usr/local/bin/aws: __strdup: symbol not found
Error relocating /usr/local/bin/aws: __memcpy_chk: symbol not found
Error relocating /usr/local/bin/aws: __vsnprintf_chk: symbol not found
Error relocating /usr/local/bin/aws: __strcpy_chk: symbol not found
Error relocating /usr/local/bin/aws: __fprintf_chk: symbol not found
```

Turns out this is a known issue: https://github.com/aws/aws-cli/issues/4685

**Comment by nbeloglazov** [comment]
@avrittrohwer I don't think this is completed given that we haven't switched to docker by default?

**Comment by avrittrohwer** [comment]
Yes I did not mean to close the entire issue.  I meant to mark that the above comment has been resolved
