### ISSUE TITLE
(WCAG 2.1) Use thicker border around language selector dropdown menu when selected

### ISSUE THREAD

**Issue by jeanniefu** [civiform/civiform#3558]
Required to meet WCAG 2.1 guidelines. Identified during an accessibility audit against WCAG 2.1.

**WCAG SC**:  [1.4.1. Use of Color ](https://www.w3.org/TR/WCAG21/#use-of-color)

**Observed results**: The focus indication for 'Select languge' control in the header is relying solely on color. This is hard to see for users who have low vision and/or are color blind.

**How to fix**: Use thicker border to indicate focus so this is more distinguishable to users.

![image](https://user-images.githubusercontent.com/9094240/192905118-fcb6ebc5-fe7a-4e34-9b77-285e0d75ea50.png)
![image](https://user-images.githubusercontent.com/9094240/192905130-06abb633-a01f-4f60-b263-ea398050b4ea.png)

**Comment by rahaghas** [comment]
Instead of changing border thickness which mak make the interaction jumpy, my suggestion would be a starker and more distinguishable UI on hover/focus:
<img width="435" alt="Screen Shot 2022-09-29 at 1 39 58 PM" src="https://user-images.githubusercontent.com/103459221/193103982-1136abec-9991-4ab4-9e48-b2cf47e7e574.png">
