### ISSUE TITLE
Datetime Values in Data Exports

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#3607]
**Describe the bug**
Data exports display datetimes in UTC while the UI shows them localized. This causes confusion for end users.

**To Reproduce**
View an application in the admin pages `/admin/programs/:programId/applications` and note the date shows as PDT/PST.

![image](https://user-images.githubusercontent.com/195162/193691128-977bad56-ef9a-4268-a189-6f65cd37881c.png)

Do a demographics export or a program export (csv or json). Look at the dates in the export file. They are UTC.

**Expected behavior**
Have the export localize the dates for a consistent end user experience.

**Comment by jessbumblebee** [comment]
I'm planning to go for the following  Alternative option instead of localizing the time in the data files:
- Make it clear in the csv that it is UCT by appending UCT to the time
- List the UMT time when the report is generated by replacing the area in red in the screenshot with 2022/10/03 at 10:53 AM PDT (5:53 pm UDT)

Reasoning
The consequence of localizing the time in the data files would be that data is not consistent across different time zones and context information about where it was created is needed to read the data correctly.

I'm following up to figure out if a change in the csv file could break the flow for civic entities and requires communicating the change.
Either way, adding "UCT" in the files would break any existing flows that rely on the csv format less than a full format change.

**Comment by gwendolyngoetz** [comment]
I think that still might result in confusion for the end user seeing localized values in the ui and utc in the export. I think the ui is localizing the time based on the timezone specified in the application.conf but I'll have to check when I'm at my desk. 

@elisekalstad since this was something you found what are your thoughts on what will make it easiest for staff to look at?

**Comment by shanemc-goog** [comment]
Another question Elise:  When the exported data is used, do those systems understand a timezone in the date or do they assume a certain one?

**Comment by jessbumblebee** [comment]
![Screenshot from 2022-10-21 17-19-09](https://user-images.githubusercontent.com/26064282/197244827-a9428062-a607-4739-a5f4-695f9916587d.png)

To add some color, this is is what I had in mind for the UI

Additionally we could change the format in the data to read as 
submit_time       |    2022-10-03 17:53:49.659845UTC   
in the above example sent by Gwen



The example which I was thinking of where a localisation would cause trouble is if a state that spans two time zones starts using civi form.

**Comment by jessbumblebee** [comment]
This line from Application.java looks like it's using server time of whatever machine the server is running on to set submit times.

https://github.com/civiform/civiform/blob/ca7024022015be90344738652590fbf852d6cf6e/server/app/models/Application.java#L123

**Comment by gwendolyngoetz** [comment]
[Here's the value](https://github.com/civiform/civiform/blob/main/server/conf/application.conf#L600) in the configure I was referring to earlier. That's what is used by the ui.

**Comment by gwendolyngoetz** [comment]
Thinking about it more if a Civic Entity does span multiple time zones (like a few states do) they still have to pick one when we set up the application.

**Comment by jessbumblebee** [comment]
Ah yes, my bad, the time zone is applied in the formatting in the step after getting the time from the application.

**Comment by jessbumblebee** [comment]
Let's see what Elise says too.
Personally I think that this could cause problems in the long term if the system gets used more broadly and potentially for users who are none technical and do not know how to figure out why the time is wrong.
It is a corner case however, and I'm likely the person with the least knowledge about the use cases on this thread.

If we think that the potential future issues are too much of a corner case to worry about, I would suggest that we include the time zone in the csv file. While it would not do much now, it would keep a back door for migrating data if required.
This is unless a change to the csv format would already cause major issues for existing deployments such as Seattle?

**Comment by elisekalstad** [comment]
Hi All, Good questions and apologies for the slow response. Here are my thoughts, happy to hop on a call today, if that's easier:
**Recommendation:** If possible, keep it consistent with **local time across the UI, CSV export, and display.** 

**Problem:** I believe the UI is in UCT, the Display is in Local Time, and the Export is in UCT, if I'm tracking accurately. Staff are confused because applications in UCT often show up as a day later than they would expect (For example, an application submitted on 10**/21** at 9:00 pm shows up the next day on 10**/22** at 4:00 am because of the 7 hour time difference. So staff are missing applications when they select the most recent date on the UI date picker. I would assume all entities operate within their timezone--UCT isn't a common timezone for government operations, that I know of.

The program staff  review applications using the CSV export. Excel doesn't pick up on the current formatting to recognize it as a date and time. Staff must do calculations (like a CONCATENATE) to extract just the date piece of the data string or just the time piece.
![Timezone Mapping](https://user-images.githubusercontent.com/86082659/197292028-3dd4755b-446f-452b-ae62-677d132ee2c4.jpg)

**Comment by jessbumblebee** [comment]
Hi Elise

Thanks for the additional context. A few follow up questions:

1) What are you referring to when you say UI versus Display? What my change will aim to do is that the date and time marked in red on the first Screenshot Gwen provided will also be used in the csv and json instead of UTC. Where can I find the third place that displays a time and needs to be consistent?

2) You say that admins use Excel and that " Excel doesn't pick up on the current formatting to recognize it as a date and time". I'm not too familiar with Excel, but is there a better format we could use so that excel recognises it automatically? If it's just a matter of formatting (e.g. splitting the date and time into two fields or using different separators), then now could be the time to make their lives easier with little extra effort and without changing the data format twice... Do you have Excel yourself?  If you could provide an example of what a date and time should look like in the csv and json, I could change that too as part of the same modification. I don't have Excel, but guess that you could create an Excel sheet with a date column and save, download or export it as a csv. That csv would then show us the format.

**Comment by elisekalstad** [comment]
Hi @jessbumblebee, All good questions!

I hope this provides clarification, let me know if it doesn't though. Always happy to chat :)

1. I added a few labels to clarify UI vs. display. Matching the red date/time from Gwen's screenshot is perfect!
2. Yes! That wound be amazing!!! The preferred date/time format is MM/DD/YYYY HH:MM:SS PM for example, 10/20/2022 7:03:40 pm. It would make so much easier! The date/time currently has Ts and Zs and a series of 6 numbers after the seconds. I end up just working around it.

![Time date stamp](https://user-images.githubusercontent.com/86082659/198112180-2e04d8c2-0814-4650-a0c2-733aeb53b73a.jpg)

**Comment by msprenke** [comment]
Completed
