### ISSUE TITLE
The State dropdown in the UI is slightly misaligned

### ISSUE THREAD

**Issue by swatkat1** [civiform/civiform#3792]
**Describe the bug**
The State dropdown in the UI is slightly misaligned

**To Reproduce**
While the applicant fills an address question, it is observed to be slightly misaligned. This is dues to the inherent feature of "SelectWithLabel". Since the solution is non-trival, a little indepth look at the UI components is needed.

**Expected behavior**
The dropdown should be aligned to the City and Zip textboxes.

**Screenshots**
![image](https://user-images.githubusercontent.com/101214724/201197739-d1e4ab4b-2f9a-4cb8-afcd-5b689d146305.png)

**Additional context**
This is part of fixing the issue https://github.com/civiform/civiform/issues/1485

**Comment by swatkat1** [comment]
This issue was looked at by 4 different experts, its solution isn't trivial. There is close to 5 pixels height difference. The way FeildWithLabel is aligning with the SelectWithLabel and how the values are getting pulled need to be looked at in detail.

**Comment by greg-hyde** [comment]
It looks like what's happening here is that the input and select both have a style that sets line-height, which increases the height of the input element but has no effect on the select element. The height difference doesn't seem to be specific to the state dropdown, but is visible here because it side by side with the input
