### ISSUE TITLE
Standardize Logout Process

### ISSUE THREAD

**Issue by michaelzetune** [civiform/civiform#4359]
## Current State

Pac4j handles the logout process for us with [`OidcLogoutActionBuilder`](https://github.com/pac4j/pac4j/blob/master/pac4j-oidc/src/main/java/org/pac4j/oidc/logout/OidcLogoutActionBuilder.java). Among other things, this class creates a Logout action that includes an ID token as a query param (`id_token_hint`). Importantly, this is part of the framework code that is supposed to handle a complex piece of authentication *for us*.

We override this class with [`CiviformOidcLogoutActionBuilder`](https://github.com/civiform/civiform/blob/main/server/app/auth/oidc/CiviformOidcLogoutActionBuilder.java), which overrides `getLogoutAction`. You can see the diff between these [here](https://www.diffchecker.com/fTivK5qk/). Notably, the logic is *mostly* duplicated. The differences are:

1. We use a [`CustomOidcLogoutRequest`](https://github.com/civiform/civiform/blob/main/server/app/auth/oidc/CustomOidcLogoutRequest.java) instead of the standard `LogoutRequest` that pac4j uses. I've simplified this class in earlier PRs, but the reason for its existence at this point is (1) to allow us to insert a custom post-logout redirect URL and (2) to fix a URI fragment issue for Seattle.
2. We allow a `postLogoutRedirectParam` to be used from the application config (retrieved in the `CiviformOidcLogoutActionBuilder` constructor), which later gets passed into the `CustomOidcLogoutRequest`.
3. The `OidcLogoutActionBuilder::getLogoutAction` takes as a third parameter a `UserProfile`. In the standard implementation, this is always an `instanceof` `OidcProfile` - and this fact is really an implementation detail of pac4j. However, we expect the in our overidden implementation for the `UserProfile` to be an `instanceof` `CiviFormProfileData`. As a consequence, we cannot replicate the logic to get the ID token from the `OidcProfile` [the way that pac4j does](https://github.com/pac4j/pac4j/blob/c3ef714701086053e7be95cf93f51f995d9df643/pac4j-oidc/src/main/java/org/pac4j/oidc/logout/OidcLogoutActionBuilder.java#L53) in the base implementation.

## Next Steps

Adding an ID token member to [`CiviFormProfileData`](https://github.com/civiform/civiform/blob/main/server/app/auth/CiviFormProfileData.java) is tempting, but it isn't clear where to add it, where to get it from, or where the pac4j framework is getting the exact `CiviFormProfileData` instance from when it internally calls (our implementation of) `getLogoutAction` in `CiviformOidcLogoutActionBuilder`.

Instead, it seems more realistic to make `CiviFormProfileData` inherit from `OidcProfile`. In theory, this should allow us to retrieve the ID token in our overriden implementation.

Later, though (as part of this issue), we should stop overriding this method if at all possible. The implementation plan below outlines how.

## Implementation Plan

1. #4361. 
It's possible that this will involve a significant refactor because the class is also used in SAML code, which is orthogonal to OIDC authentication.
2. #4339.
Remove the `CustomOidcLogoutRequest` class that `CiviformOidcLogoutActionBuilder` uses  - its use cases are no longer applicable, so we can migrate to the standard `LogoutRequest` class (which is the base class of `CustomOidcLogoutRequest` anyways).
3. Remove the `CiviformOidcLogoutActionBuilder` child class of `OidcLogoutActionBuilder` and let pac4j do all the logout work.

## Related

[Stackoverflow question](https://stackoverflow.com/questions/75688709/getting-id-token-for-logout/75693656#75693656) about this (asked by me).

Allowing the ID token to be retrieved in our overidden method (and eventualy, allowing pac4j to do it itself), should resolve #3863. Verify this independently.

Relates to #4280.

Many attempts at getting and passing the ID token are [here](https://github.com/civiform/civiform/commit/1f05c1d94dc43ae3c94c8d5562afa1cad596c214) for posterity.

**Comment by michaelzetune** [comment]
cc @yotommy

**Comment by yotommy** [comment]
Posted to StackOverflow: [ID token is cleared during storage to session](https://stackoverflow.com/questions/77062229/id-token-is-cleared-during-storage-to-session).

**Comment by yotommy** [comment]
TDD: [Design: Supporting OIDC Logout](https://docs.google.com/document/d/1K2bZSYgoExJgAs-oVf4CkqQ6ZFoVY9fvN8fwRMzQwBQ/edit)

**Comment by yotommy** [comment]
In testing the proposed design, `play-pac4j` demonstrated a curious behavior: it *removed* the `id_token` from the `OidcProfile` before storing it to the session, which defeats the purpose of the whole endeavor. The [behavior](https://github.com/pac4j/pac4j/blob/eef713772246303327f9239631726a0bb48afef4/pac4j-oidc/src/main/java/org/pac4j/oidc/profile/OidcProfile.java#L260-L264) can be overridden, but I wanted to understand the rationale for this behavior.

I posted a question to StackOverflow: [ID token is cleared during storage to session](https://stackoverflow.com/questions/77062229/id-token-is-cleared-during-storage-to-session). The `pac4j` team explained the behavior is due to use of the `PlayCookieSessionStore`, which introduces a limit of 4KB for the session cookie.

In my Okta testing with a profile with a single claim, the cookie size (including the id token) is 3215 bytes.

Exceeding the limit would prevent any state from being stored, which would prevent admin or applicant access. Not good!

If we need more headroom, then we can use the `PlayCacheCookieStore`. Since this is a cache, entries are subject to eviction. However, the cookies are pretty small, so we may be able to minimize this situation. (If the profile is 5 KB, we can fit ~200,000 into 1 GB of RAM.)

Different cache implementations are described in [The Play cache API](https://www.playframework.com/documentation/2.8.x/JavaCache).

The simplest cache implementation is in-process (via Caffeine), which is already [configured](https://github.com/civiform/civiform/blob/fe12157fe719ebc087904c5e64d708627ae962e8/server/build.sbt#L19-L21) in our server. There is support for distributed caching based on third-party plugins for `memcached` and `redis`. [AWS ElastiCache](https://aws.amazon.com/pm/elasticache/) can be used as the backend. All of this, of course, introduces extra system complexity.

**Comment by yotommy** [comment]
Added documentation to wiki: [Enhanced OIDC logout](https://github.com/civiform/civiform/wiki/Authentication-Providers#enhanced-oidc-logout)

**Comment by yotommy** [comment]
We decided not to add a distributed cache (see [Decision: avoid a distributed cache](https://docs.google.com/document/d/1D-lOTg6kTt6ZBux8CB8jFbXPHvqICx1F74LZb2fpH7Q/edit#heading=h.bknox3ib8wpb)). Instead, we store the ID tokens in the `accounts` table of the db (one token per session, potentially multiple simultaneous sessions per account).

The design is documented in [Design: Supporting OIDC Logout](https://docs.google.com/document/d/1K2bZSYgoExJgAs-oVf4CkqQ6ZFoVY9fvN8fwRMzQwBQ/edit).
