### ISSUE TITLE
Hidden programs are inaccessible for TI Clients

### ISSUE THREAD

**Issue by swatkat1** [civiform/civiform#4495]
**Describe the bug**
Hidden programs are inaccessible for TI Clients

**To Reproduce**

1. Create a hidden program with name say Test.
2. Try to access the program as an applicant- with /test appended to the CiviForm URL. (eg. https://civiformstage.seattle.gov/programs/test )
3. Go to TI dashboard and create a new Client.
4. Got to the applications page of the Client.
5. Try accessing the hidden program with programs/test appended to the URL.
6. It doesn't load

**Expected behavior**
Hidden programs should be accessible by both TI Clients and residents.

**Screenshots**

View from residents: on typing https://civiformstage.seattle.gov/programs/test
![image](https://user-images.githubusercontent.com/101214724/227646348-dd5697ca-4902-4e30-a644-a738165f7774.png)

**Comment by bion** [comment]
The first screenshot has a URL of the pattern `/applicants/:applicantId/:programSlug` which is not a valid URL pattern.

The valid URL pattern for accessing a program using its slug is `/programs/:programSlug`.

**Comment by swatkat1** [comment]
@bion  - The TIs were unable to test the Fresh Bucks form on Friday which is a hidden program. Unless it is an expected behavior this issue shouldn't be closed and needs to be investigated. They accessed the program using program/programslug in the same session after logging in as TI. @elisekalstad  - Please feel free to add in more details.

**Comment by elisekalstad** [comment]
Elise to update the issue--screen shots too!

**Comment by elisekalstad** [comment]
The issue is actually slightly different: The TI is able to see the hidden program by using the direct link. But the TI is unable to apply for the program on behalf of a client using the current workaround. (Long term fix is to allow CiviForm Admins to specify programs that are visible for selected CBOs. Design currently underway by @msprenke ).

Steps to reproduce:

1. Megan, the TI, logs into CiviForm as a TI
2. Clicks Add Client
3. Adds Troy, the client
![image](https://user-images.githubusercontent.com/86082659/229948762-9957aeaf-1de6-462b-b923-c4b2e34aa848.png)

5. Clicks Applicant Dashboard
![image](https://user-images.githubusercontent.com/86082659/229948826-af3001fa-4b87-479b-baaf-f0ff0a627280.png)

7. Pastes in the direct program link: https://civiform.seattle.gov/programs/cboenrollment
8. Form shows that she is applying on behalf of herself, and not her client, Troy.
![image](https://user-images.githubusercontent.com/86082659/229948889-8e3db4c1-3ed0-4690-8997-ec648c7cd1d6.png)

**Comment by msprenke** [comment]
Working as designed.  Will address with new request to allow programs to be visible only to TIs
