### ISSUE TITLE
Applicant who is managed by a TI can see TI_ONLY programs

### ISSUE THREAD

**Issue by nb1701** [civiform/civiform#4857]
**Describe the bug**
[This](https://github.com/civiform/civiform/blob/39b6db15f773f918d964b32aa68d16edd2f82079/server/app/services/applicant/ApplicantService.java#L849C99-L851) uses the wrong function to determine if an account is a TI account. This kind of works, because when a TI is view the index page as one of their clients, `getManagedByGroup` is going to be present since the TI is managing them.  However, this means the applicant can then log in and see that same program that is supposed to be visible only to TIs.  Instead, this should be using `getMemberOfGroup`, which indicates an account is a member of a TI organization.

**To Reproduce**

1. Create a program with TI visibility.
2. Create an applicant as TI (give the account an email of something@example.com, since our dev environment always adds @example.com to logins).
3. Note that when applying as this applicant, you can see the program.
4. Log out.
5. Log in as that account (something@example.com). Note that you can still see the program.

**Expected behavior**
A TI, viewing the index page as an applicant, can see the TI_ONLY program.  An applicant managed by a TI, when logging in on their own, can not see it unless they've applied to it.

**Comment by bion** [comment]
@elisekalstad I had a discussion with @swatkat1 about whether or not this is intended behavior.

Current behavior: if an applicant logs into their TI-managed account, they can see the TI-only programs and apply for them.

My guess is that the *desired* behavior is: if an applicant has an existing (either started but not submitted or submitted) application to a TI-only program, that they can see it when they login, but should not be able to see it otherwise.

Current proposed bugfix (this issue): only the TI can see the program and the applicant can never see it, regardless of their application status to the program.
