### ISSUE TITLE
Include accents in CSV export

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#5057]
**Describe the bug**
As a program admin, when I export applicants into a CSV, any accents (such as in someone's name) are shown with symbols. I'm not sure if this is within the power of CiviForm. But it would help program admins to prevent them from manually editing names to include proper symbols.

**To Reproduce**

1. Submit an application to a test program with accents on the letters
2. Login as a Program Admin
3. Export the applications to CSV
4. See erroneous symbols in the export

**Expected behavior**
Accents carry through in the export

**Screenshots**
Export with accent:
![image](https://github.com/civiform/civiform/assets/86082659/ab55ef4f-5e70-470d-8a0b-3152c272a707)

As a view within CiviForm: 
![image](https://github.com/civiform/civiform/assets/86082659/1075f67a-0308-4be1-8f1b-c28a9004b42a)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
This may be something that is fixed when exporting to a CSV and not within the scope of CiviForm.

**Comment by gwendolyngoetz** [comment]
The text is exported correctly in UTF-8. The problem is that Excel doesn't like the character encoding. 

@elisekalstad Here are two workarounds for now:

### Option 1 - Use Notepad (Faster, but might be confusing for people)

- Open the CSV in Notepad.
- Click “File” and “Save As”.
- In the new popup that displays,  select “ANSI” from the “Encoding” field.
- Click “Save”.
- Now, you should be able to open the file in Excel and display the characters correctly.

### Option 2 - Use Excel (More steps, but might be easier for people)

- Open Excel
- Click “File” and “New”
- Click on the “Data” tab
- Click “From Text/CSV” and select the CSV file
- Click "Load" in the popup that appears
- Excel should now show you the CSV file and display the characters correctly.

**Comment by elisekalstad** [comment]
@gwendolyngoetz -- You're the best! Thank you for the instructions. Option 2 probably works best with their current workflow. Good to close? Closing :)
