### ISSUE TITLE
Don't try loading data in /dev/seed

### ISSUE THREAD

**Issue by nb1701** [civiform/civiform#5210]
If there's a problem loading programs and/or questions on staging, we are unable to load /dev/seed in order to clear the database, as this page parses the programs and questions in the database. Clearing the database then requires manually curling a POST to /dev/seed/clear.

Instead, we should have /dev/seed just include the buttons, and create a separate button to view the data in the database, to avoid this kind of situation. We may need an additional indicator that adding a program/questions was successful since we're not loading the data on this page now.  While we're at it, an additional button to take you to the index page would be nice.

**Comment by azhangggggg** [comment]
To conclude this is what this issue is asking 
1. having dev/seed page only include current buttons like `Seed sample programs` `Seed sample questions` etc. 
2. a new button `View data` on dev/seed to show user the data if it's clicked
3. a banner indicates if adding a new program/question is successful.

@nb1701 I'll work towards this direction but let me know if my conclusion isn't right to what you're talking abt up there.
