### ISSUE TITLE
"Return" should trigger an action

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#5464]
**Is your feature request related to a problem? Please describe.**
As a Program Admin, I want to be able to use my "Return/Enter" key to trigger an action. When I am searching for an application by name, email or ID, I want to be able to hit "Return" and see the search result. I currently need to click on the "Filter" button with my mouse each time.

**Describe the solution you'd like**
A Program Admin can hit "Return" and have their input trigger an action in CiviForm, such as Filter.

**Additional context**
![image](https://github.com/civiform/civiform/assets/86082659/74547af8-108a-4d9d-acb1-f241ff755312)

(Would expect the blue-highlighted button to correspond the hitting "Return".)

**Done when**
I can hit "Return" on my keyboard and have my search results display.

**Comment by elisekalstad** [comment]
Feedback received via program admin staff at the Parks Dept.

**Comment by elisekalstad** [comment]
**Should also be consistent for TI experience searching for clients**

**Comment by swatkat1** [comment]
@elisekalstad  - This work item needs a second assessment due to https://github.com/civiform/civiform/issues/3872. Currently submission on "Return" is disabled all throughout CiviForm. It also conflicts with a11y too.

**Comment by elisekalstad** [comment]
Thanks @swatkat1 -- just to clarify that this request is for the Program Admin experience when filtering for applications. This is not related to Applicant experience for submitting an application.

**Comment by swatkat1** [comment]
Yes but this is disabled throughout the code. Not just for applicant experience. Also, for program Admin and CiviForm Admin experience. According to the ticket, they were seeing weird behavior due to enabling "Enter" on form submissions. /**
 

* Disables default browser behavior where pressing Enter on any input in a form
 * triggers form submission. See https://github.com/civiform/civiform/issues/3872
 */
