### ISSUE TITLE
Implement USWDS "official government website" super banner 

### ISSUE THREAD

**Issue by isabelcshaw** [civiform/civiform#5569]
**Describe the solution you'd like**
In order to continue to build trust with applicants and TIs, we want to confirm with users that the CiviForm website is an official government website of their city or state. To help do this, we are going to implement the USWDS official government website component / super banner. 

**Done when**
This issue is done when the banner and it's expanded view are complete and @sijiayam confirms that the implementation matches the design here: 
[Zeroheight documentation](https://civiform.zeroheight.com/styleguide/s/109871/p/85d24f-super-nav/b/32e1a2)
[Figma component](https://www.figma.com/file/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?type=design&node-id=1100-10842&mode=design&t=MlzTVLY1wNKXkeue-4)

Expected behavior:
- The banner can expand and close, interaction matches the USWDS compoent
- Our super nav does not have a flag icon
- The banner is displayed above all content on all pages, for all implementations
- The zeroheight documentation displays a dark and light version, for this issue we are only implementing the default (dark) version

References:
- https://designsystem.digital.gov/components/banner/
- https://www.seattle.gov/ 
- <img width="766" alt="Screenshot 2023-09-11 at 8 35 26 AM" src="https://github.com/civiform/civiform/assets/12836913/a08813d8-1192-4f81-b80d-63d067485b14">

As a super banner, it is always visible on every view.

**Comment by isabelcshaw** [comment]
@sijiayam will link to the component

**Comment by sijiayam** [comment]
@melanie-exygy I have updated the figma link as well attached a zeroheight documentation link with colors.

Let me know if that works for you/any outstanding questions

**Comment by melanie-exygy** [comment]
@sijiayam and I discussed that adding the banner brings out some design debt that we should address in separate issues.  Two design debt problems are:  
- We need a full page container which includes the header and footer and which has a max-width that is less wide than we have now.  There should be space on both sides when in a wide view.  A good example is [ seattle.gov](https://www.seattle.gov/).
- Admin and applicant facing pages should have a consistent look, especially for the nav.  For example, the logo should be the same and the nav in both views should either be fixed or not fixed.  Right now, it is not fixed in the applicant-facing pages and fixed on the admin pages.
