### ISSUE TITLE
Remove applicant IDs from URL paths

### ISSUE THREAD

**Issue by bion** [civiform/civiform#5576]
## Overview

When applicants use CiviForm, nearly all of the URL routes they interact with are prefixed with their applicant ID in the form `/applicants/:applicantId`. For example, landing on the homepage redirects (after creating a guest account for the visitor) to `/applicants/:applicantId/programs`.

This is an issue when applicants share URLs to CiviForm, since whoever they share it with will be attempting to access the sharer's applicant and so CiviForm detects unauthorized access and redirects them to the homepage. This prevents, for example, applicants from being able sharing direct links to specific programs with others.

## Implications for TIs

The original reason for doing this was for simplicity so that TIs and applicants would have the same routes -- implementation was quicker this way. It also allows multiple TIs who work with the same client to share URLs of a client's application with one another for collaboration.

## A possible improvement

One way to improve this could be to create a separate set of routes for the applicant only that do not include the `/applicants/:applicantId` prefix and retain the original routes for the TIs' use only.

For applicants, rather than referencing the URL for the current applicant, the CiviForm server would detect the account type as an applicant and resolve their ID from session state.

**Comment by yotommy** [comment]
To remove the applicant id from URLs, we obviously need new entries in [`routes`](https://github.com/civiform/civiform/blob/main/server/conf/routes). Play doesn't allow controller methods to be overloaded, so we need new controller methods. (There are some ways of specifying default parameter values, but that's only for parameters that are specified in the query string.)

Each of the applicant controller methods needs to get the applicant id _somehow_. If it's not in the URL, we should get it from the session. We already store the `pac4j` user profile in the session, with the invariant that the id of the profile is the same as the id of the associated account. So it's simple to get the account id from the request.

But we need to get the applicant id, not the account id. To avoid doing an extra db fetch, we will also store the applicant id in an [attribute](https://www.javadoc.io/static/org.pac4j/pac4j-core/5.7.0/org/pac4j/core/profile/BasicUserProfile.html#addAttribute(java.lang.String,java.lang.Object)) of the user profile. 

(Note that a new db query is not strictly required, as the account is fetched when we [check the authorization](https://github.com/civiform/civiform/blob/3f1f93425e37dfd07f02d4f13e76145061a7e82f/server/app/auth/CiviFormProfile.java#L204) for each action. However, this currently happens _after_ we [fetch some information](https://github.com/civiform/civiform/blob/b5b49495a2bf483e043cabf1441238098ac69bd5/server/app/controllers/applicant/ApplicantProgramsController.java#L71-L72) about the applicant, so that would require quite a bit of refactoring.)

Now that we have two routes/controller methods for each applicant action, we need to populate the appropriate URLs for different scenarios. Every place that we calculate a route for a controller method, we need to decide if this should be the controller method for applicants or the one for TIs. We can handle this by providing the [`Role`](https://github.com/civiform/civiform/blob/main/server/app/auth/Role.java) corresponding to the user profile to the appropriate views.

**Comment by yotommy** [comment]
Once applicants get a new profile, it will contain the application id attribute, but we need to ensure that existing user profiles (without the attribute) continue to work with the new scheme.

**Comment by yotommy** [comment]
We decided we can enable this for all deployments in this [Slack thread](https://civiform.slack.com/archives/C035N9KCR0U/p1704223097388309).
