### ISSUE TITLE
Add Program Admin navigation pane when viewing single application

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#5594]
**Is your feature request related to a problem? Please describe.**
As a Program Admin, I receive an email when there is a new application submitted. I can click on the direct link to view the application. But once I am viewing one application, I cannot click a button to go to the Program Admin "home page" to view all applications or reports.

**Describe the solution you'd like**
Add the Navigation bar to the top of the page when viewing an application from the email alerts.

**Additional context**
**Current state:**
![image](https://github.com/civiform/civiform/assets/86082659/1f2f6b8f-8414-44a5-afc9-34aca350223d)

**Ideal future state:** 
![image](https://github.com/civiform/civiform/assets/86082659/33eec9e0-a988-42cd-b1be-3ff457ebf794)

**Done when**
Program Admin can click a link to a single application via an email, can view that application, and can navigate using one click to view the admin page with all applications and reporting.

**Comment by gwendolyngoetz** [comment]
What is happening is that the link in the email is going directly to the application details page. This page is what is displayed in an iframe on the application search. Rather than add navigation to this page, it would be better to change the url in the email. 

We already have the info we need to build the url so it makes more sense to go to the search page and have it auto load the application in there.

That would be this url: https://hostname/admin/programs/{program_id}/applications?page=1&selectedApplicationUri=%2Fadmin%2Fprograms%2F{program_id}%2Fapplications%2F{application_id}

**Comment by msprenke** [comment]
moving this to ready for development as a requirements doc should not be required.  The change is outlined above to build the URL as noted  by Gwen.
