### ISSUE TITLE
Text overlap on mobile 

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#5822]
**Describe the bug**
As an applicant using an IPhone to apply to the Seattle Preschool Program, the "repeated entity type - Remove" button overlaps with the repeated entity.

See screenshot for example.

**To Reproduce**

1. Using an iphone
2. Go to civiform.seattle.gov
3. Click on 'Seattle Preschool Program
4. See that the "remove" button overlaps with the repeated entity name

**Expected behavior**
Auto-size to the appropriate device

**Screenshots**
Attached

**Smartphone (please complete the following information):**

- Device: iPhone12

![Bug_overlapping text_mobile](https://github.com/civiform/civiform/assets/86082659/c246201d-345d-4148-ab5a-077b3542eac8)

**Comment by elisekalstad** [comment]
One possible solution is to have the button say **"remove"** (take out the repeated entity name").

**Comment by elisekalstad** [comment]
@isabelcshaw -- To consider for Product Development committee. Would this need full project approval?

**Comment by elisekalstad** [comment]
![image](https://github.com/civiform/civiform/assets/86082659/b474facf-2d4a-410f-bd72-540e10246a99)

**Comment by elisekalstad** [comment]
@msprenke -- I've exhausted my design skills, any other ideas for this one?

**Comment by avaleske** [comment]
This seems like a bug so imo it shouldn't need product design committee approval. (Also tagging @nb1701 for visibility in case  the seattle status label is keeping it out of your triage dashboard)

**Comment by rockycodes** [comment]
Just fyi the numbers on the labels were added as an accessibility recommendation: https://github.com/civiform/civiform/issues/2624

So we may want to keep them on desktop if possible. We could also flex this so the "remove" button is below the entry field at small screen sizes instead of next to it.

**Comment by Subzidion** [comment]
It looks like the issue here is Safari increases the width of the button to keep the "Adult/Parent/Guardian" text on a single line, creating the overlap. (Interestingly, Firefox doesn't do this, splitting the text on the /). Fixing this can be achieved by inserting the [`<wbr>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr) after the backslashes. More generically, adding the Tailwind [`break-words` class](https://tailwindcss.com/docs/word-break#break-words) (along with `max-w-full`) would allow the long String to be broken up within the button. Another easy option is to just add spaces before/after the slashes in the text: "Adult / Parent / Guardian" which will make the line breaking work automatically.

The `<wbr>` option is Number 1, and the `break-words` (plus `max-width: 100%`) option is Number 2 (iPhone 12 Mini screen size):
<img width="425" alt="Screenshot demonstrating different button configuration options" src="https://github.com/civiform/civiform/assets/3676230/012af314-6298-4153-baa2-36bae89e5cda">

**Comment by elisekalstad** [comment]
Thanks for taking a look @Subzidion -- I can add spaces to the text for the easy workaround. If it helps, the overlap I experienced was on an iphone using chrome. Thanks for diving into this one!
