### ISSUE TITLE
Restrict characters allowed in option admin names

### ISSUE THREAD

**Issue by avaleske** [civiform/civiform#5839]
Building on #4862, restrict option admin names to a-z, A-Z,0-9, hyphens, and dashes.

Existing option admin names would be unaffected.

The goal is to make it easier to write code that processes these admin names. For example, writing SQL to target `option_1` is much easier then `option "alpha" #1`.

Approved by Exygy, Seattle, Arkansas, and Bloomington.

**Comment by inghamn** [comment]
It would be nice to have a way to audit and alter all the admin names for the question options.  Because initially, the admin names are the verbose human typed sentence, the vast majority of them will be "not great" for use as CSV column names.

It would be nice if we could clean up all the admin names before moving forward with using the API and data export.  Changing the admin names would certainly be something that would break any existing automations that expected certain column names; however, it would be best to get that pain over early and all at once.

**Comment by avaleske** [comment]
@inghamn I agree that the initial admin names aren't great for use as CSV column names or values in the JSON export, but as you noted, we didn't want to break any existing integrations.

As a workaround: While the admin names for an existing question option can't be changed, you can change the admin name by removing and re-adding the option.

**Comment by inghamn** [comment]
The character restriction makes perfect sense, I don't see any problems with the character restriction.

You are correct in identifying that the people coming up with the questions are not the people who would be able to provide a good column label for integrations.  It is my experience that column label problems are revealed much later when attempting integrations.
