### ISSUE TITLE
Add evolution for applicants table

### ISSUE THREAD

**Issue by nb1701** [civiform/civiform#6394]
#### Describe the solution presented in this issue.
Add an evolution that modifies the `applicants` table as defined in the TDD.  This adds the following columns:

- `first_name` - varchar
- `middle_name` - varchar
- `last_name` - varchar
- `email_address` - varchar
- `phone_country_code` - varchar
- `phone_number` - varchar
- `date_of_birth` - date

Indexes should also be applied to each of these columns.  First/middle/last names and phone number should use a GIN index on a trigram using the pg_trgm extension.  Email and DOB should use default btree indexing.

Include downs to drop the columns and indexes.

See https://github.com/civiform/civiform/commit/fe9f0d1e34296dac643da6249c2d7b70abd83eb3 (this can probably be used as-is).

#### Additional Context
[TDD](https://docs.google.com/document/d/13xTLRl82gDD0VajM68gVdOGUV6alXi_mtluf1uUT1Lo/edit)

#### Done when:
What criteria need to be met for the issue to be finished? 
- [x] `applicants` table has the new columns and indexes

**Comment by inghamn** [comment]
When upgrading to the latest version, our instance fails on this evolution.  The civiform database user does not have anough permission to run the create extension command.  

Our current pattern is to create the extensions when creating the database, before loading data.  When we manually create the extension ahead of time, the evolution crashes because the extension already exists.

Do you typically grant the civiform database user role SysAdmin permissions?

**Comment by inghamn** [comment]
Rock on, we granted civiform superuser, ran the evolutions, then revoked superuser.
