### ISSUE TITLE
Time out error when downloading CSV of applications

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#6573]
**Describe the bug**
As a Program Admin I'd like to download a CSV of recent applications. I am unable to download the CSV without CiviForm timing out first. I tried to download the 1 application that showed when filtering for just 1 day and still had the error.

**To Reproduce**

1. Login as a Program Admin
2. Click on the "Parks Scholarship - Current" program
3. Set the date filter for a few days
4. Filter results
5. Download the CSV
6. See timeout error

**Expected behavior**
I should be able to export the CSV without it timing out.

**Screenshots**
![image](https://github.com/civiform/civiform/assets/86082659/37766be2-9d93-4ced-b08e-558dd26c068a)

(See date range selected for 1 date)

**Comment by swatkat1** [comment]
This issue has been investigated and a bug in CiviForm is identified.  The issue is - On creating new Admin Names for question options, we do not check for case sensitivity with existing admin names. There are two parts of the fixes (bug - https://github.com/civiform/civiform/issues/6605 )

1. Create a SQL query to rename the the duplicate DB's question option to something similar (append "_1" to the option) 
2. Going forward, add the case sentivity check also to new options as they are created.

**Comment by avaleske** [comment]
I opened #6607 to track writing the query to detect if a deployment has this error case.
