### ISSUE TITLE
Removing innactive TI accounts

### ISSUE THREAD

**Issue by Miguel-314** [civiform/civiform#6628]
#### Is your feature request related to a problem? Please describe.

SHA staff asked today if a staff member leaves the organization, are they still capable of signing into CiviForm and viewing or editing applications? SHA will inactivate their work email address. Does CiviForm have the ability to identify accounts with recently inactivated email addresses? 

Or does SHA (and other organizations) need to contact us to remove inactive TI profiles? 

#### What priority is this?

A clear description of whether this is high, medium, or low priority for you and why (eg, it is majorly blocking a user group, it has been requested several times, etc).

#### Associated civic entity

Is this request associated with a specific civic entity? If so, please add the associated civic entity to the label (eg, label with 'seattle' if this request is coming from Seattle admins, CBOs, or residents.

#### User Group

If this request or piece of feedback comes from a resident, add the label 'Resident feedback'.
If this request or piece of feedback comes from a CBO or TI, add the label 'TI'.
If this request or piece of feedback comes from an admin, add the label 'Program Feedback'.

#### Done when:

What conditions need to be met before this issue can be closed?

**Comment by gwendolyngoetz** [comment]
The TI user logs in via the same way as other applicants. Adding their email account to a TI organization is how the system triggers access to the TI features.

In the event the third party email provider had removed the email address, it would still be able to log in since the authentication is not tied to the third party system in any way.

There is no way to know if an external email address has been removed from a third party email provider. To remove their access we have to go in and manually remove their email address from the TI organization.
