### ISSUE TITLE
Conflicting Docs on Setting the Support Email Address

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#6636]
I found that in my prod and staging `civiform_config.sh` files I have the support email address set with `SUPPORT_EMAIL_ADDRESS`, but on my test site config I have it set with `CIVIC_ENTITY_SUPPORT_EMAIL_ADDRESS`.

`CIVIC_ENTITY_SUPPORT_EMAIL_ADDRESS` is what is listed in the sample file. `SUPPORT_EMAIL_ADDRESS` is what is listed on the docs site.

On an internal server error page on prod and staging the correctly configured email address shows. On test it shows an exygy email address which is the default fallback value.

https://github.com/search?q=repo%3Aciviform%2Fcloud-deploy-infra%20SUPPORT_EMAIL_ADDRESS&type=code

**Comment by rockycodes** [comment]
`SUPPORT_EMAIL_ADDRESS` is correct. I'll update the other references to `CIVIC_ENTITY_SUPPORT_EMAIL_ADDRESS`. It's also worth noting that `SUPPORT_EMAIL_ADDRESS` is admin writeable so it's recommended to only set it in the admin settings panel, rather than in the deployment config. It's not listed at all in the [example config](https://github.com/civiform/civiform-deploy/blob/main/civiform_config.example.sh).

**Comment by gwendolyngoetz** [comment]
If we don't want it set in the config file should it allow it to be pulled in at all then?

**Comment by rockycodes** [comment]
We do want it to be pulled in from the config for our aws staging site, for example, since that's wiped every night and we don't set values via the admin panel. But it's probably worth a larger conversation about how to manage these vars. It doesn't break anything if they're set in the config, but Bion wanted to discourage that because it could get confusing if they're set in the config file, changed in the admin settings panel, and then the value in the config doesn't match the value on the site.

**Comment by rockycodes** [comment]
@gwendolyngoetz the more I think about this, the more it seems like we should disallow setting `ADMIN_WRITEABLE` vars in the deploy configs and then add an override for it in the case of staging. I'll make an issue for that.

**Comment by gwendolyngoetz** [comment]
Probably for the best. It's really the only way I'll stop configuring it via the config file, lol.
