### ISSUE TITLE
Create default header styles for all pages

### ISSUE THREAD

**Issue by sijiayam** [civiform/civiform#7003]
Currently our header styles (ex. H1, H2, H3, etc.) are not easily readable and do not create good visual hierarchy for the user.

Styles need to be defined (either USWDS or tailwind) for our base header styles.

Requirements:
- Defining default header styles on mobile, tablet, desktop
- Accessibility guidelines for pages where default header styles may be overridden
-

**Comment by sijiayam** [comment]
Need a few main north star pages to be created before finalizing

**Comment by gwendolyngoetz** [comment]
When we validate the headings are styled as we want them and correctly ordered in the html within Northstar we need to take into account the USWDS alerts which use `H4` as the default (on non-slim alerts).

I ran into issues adding the new eligibility alert headings in both the old and northstar code where I had to override the heading on different pages because the Axe accessibility tests found either headings in the wrong order (e.g., h1-h3-h2) or gaps (e.g., h1-h3-h4).

**Comment by sijiayam** [comment]
Update: Header styles have been created. Reccomendation is to use all styles in usa-prose. https://designsystem.digital.gov/components/prose/

Accessibility guidelines need for specific components
