### ISSUE TITLE
Add Application_Note is in .csv download

### ISSUE THREAD

**Issue by Miguel-314** [civiform/civiform#7366]
#### Is your feature request related to a problem? Please describe.

More program staff are considering CiviForm as a better option for reviewing applications and managing the enrollment process. This includes more detailed use of status updates and the use of admin notes. Program staff have requested that admin notes be include in the .csv download. Currently the application status shows up in the .csv download file. including Admin note would help program staff work through the specific business process necessary to complete the enrollment process without having to go back and forth between the .csv file and the program admin view in CiviForm. 

#### Describe the solution you'd like.

text in the admin note shows up as a column with data in the .csv download file. 

#### What priority is this?

P2

#### Associated civic entity

Seattle

#### User Group

Program Feedback

#### Done when:

When program admins can see their admin notes in the .csv download file.

**Comment by elisekalstad** [comment]
Add the note as the last column please :)

**Comment by swatkat1** [comment]
The feature request was to add the Application note to the CSV export not the program's admin note. Adding the application note is not a trivial solution since the data is stored in the application_events table and for every application to be exported, we would do a lookup of the latest application note event to extract the note raising the time complexity to O(n^2) queries which would eventually fail the export and cause SQL timeout error. We need a better design on how to implement this.

**Comment by swatkat1** [comment]
TDD is required- issue to track it - https://github.com/civiform/civiform/issues/8194
