### ISSUE TITLE
TI Groups Page Loads Slowly

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#7424]
Loading the TI Groups Page is slow in Seattle (prod). 12 seconds+

`/admin/tiGroups`

The query either needs optimizing or we need to look into caching TI data

**Comment by gwendolyngoetz** [comment]
@dkatzz FYI

**Comment by melanie-exygy** [comment]
@gwendolyngoetz I just want to clarify that routes starting with `admin/tiGroups` aren't for the TI dashboard.  Those are for the admin TI configuration.  Routes for the TI dashboard start with `admin/tiDash`.

**Comment by dkatzz** [comment]
> @gwendolyngoetz I just want to clarify that routes starting with `admin/tiGroups` aren't for the TI dashboard. Those are for the admin TI configuration. Routes for the TI dashboard start with `admin/tiDash`. IMO in would be best to change the name of this issue and the description to avoid confusion.

Makes sense! Yeah I can imagine [this query](https://github.com/civiform/civiform/blob/main/server/app/repository/AccountRepository.java#L236) getting slow with lots of groups and also we load all the [members](https://github.com/civiform/civiform/blob/main/server/app/views/admin/ti/TrustedIntermediaryGroupListView.java#L129) and  [managed accounts](https://github.com/civiform/civiform/blob/main/server/app/views/admin/ti/TrustedIntermediaryGroupListView.java#L131) when we really just need the counts. Let me know if we need someone to work on this and I can take a pass.

Some ideas:
- Select only the attributes we need in the account repository query - https://ebean.io/docs/query/select
- Consider refactoring findList to findEach - https://ebean.io/docs/query/findList
- Create a query that uses [findRowCount](https://groups.google.com/g/ebean/c/gVRvP4S08-M/m/mR7AE8nrDAAJ) instead of [loading](https://github.com/civiform/civiform/blob/main/server/app/models/TrustedIntermediaryGroupModel.java#L36) the ManyToMany associations

**Comment by gwendolyngoetz** [comment]
FYI. This is now taking 35 seconds to load.
