### ISSUE TITLE
[North Star Applicant UI] Add styling for upsell/application confirmation page

### ISSUE THREAD

**Issue by greg-hyde** [civiform/civiform#7683]
Ensure that application confirmation page (for standard applications and prescreeners) has updated styling

**Comment by ssandbekkhaug** [comment]
Changing size estimate from small to medium since the [mocks](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=2459-23884&m=dev) have significant differences from the old page.

For the MVP launch, we might not be able to add "Other programs you may be interested in"

**Comment by dkatzz** [comment]
> Changing size estimate from small to medium since the [mocks](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=2459-23884&m=dev) have significant differences from the old page.
> 
> For the MVP launch, we might not be able to add "Other programs you may be interested in"

@ssandbekkhaug  That section currently exists (assuming there are programs the applicant may qualify for: <img width="1026" alt="Screenshot 2024-08-02 at 10 57 47 AM" src="https://github.com/user-attachments/assets/72214a9c-08bb-4fb2-b545-28db89a4e738">

The next steps piece would maybe be something for post mvp and the extra information on the "other programs you may qualify for" cards

**Comment by sijiayam** [comment]
QA completed and the following design QA issues opened:
- #9034 
- #9033 
- #9032 
- #9031 

Mobile experience will be tested when #9035 is complete
