### ISSUE TITLE
[North Star Applicant UI] Write TDD for North Star migration plan

### ISSUE THREAD

**Issue by greg-hyde** [civiform/civiform#7789]
Write short TDD for determining when eng effort will switch to thymeleaf and steps needed before launch

**Comment by ssandbekkhaug** [comment]
Greg's super high level idea:
1. when we're "sorta close to launch", have people switch over to writing in thymeleaf instead of j2html. Exact date depends on the intended launch date and size of the feature in question
2. Get an a11y audit from google
3. When we're actually close to launch, everyone jump on it for a couple weeks and do a couple bug bashes and everyone fix bugs

**Comment by ssandbekkhaug** [comment]
Isabel showed me [UX North Star / Thymeleaf Implementation Plan](https://docs.google.com/document/d/1o6Wmj8D66ehzzBVBizkbtb2zhf8iPOGini8HqfkRIPk/edit#heading=h.e79yz9cesjmy)
