### ISSUE TITLE
Reduce clicks to filter and download applications

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#8209]
#### Is your feature request related to a problem? Please describe.

As a Program Admin and CiviForm Admin, I would like to filter applications based on date range, name, ID, or phone number and then download the CSV export. I run into issues because there is an order of operations required, but it's not clear that there are a series of clicks needed in order to export the filter CSV.

What I do:
1) Enter start date 
2) Enter end date
3) Select Download
4) Select Current Results

I expect to see a CSV with applications from the appropriate date range. What I actually get is the entire list of applications, with no filtering applied OR often I get a timeout error. I did not select "Filter" before selecting "Download". It isn't intuitive that I need to click "Filter" first.

What I'm supposed to do to download a filtered list:
1) Enter start date 
2) Enter end date
**3) Select Filter**
4) Select Download
5) Select Current Results

#### Describe the solution you'd like.

Is it possible to add function behind the "Download" button, so that it effectively Filters AND Downloads? That would remove the need to remember to click "Filter" before "Download". 

What I'd like to be able to do:
1) Enter start date 
2) Enter end date
3) Select Download
4) Select Current Results
See filtered list of applications in the CSV

#### What priority is this?

Low, just need to remember to click "Filter" first.

#### Associated civic entity

Seattle

#### Additional Context

![image](https://github.com/user-attachments/assets/3e88a33e-c293-4c6e-a842-cece63a89cbd)

![image](https://github.com/user-attachments/assets/2e2b131b-5452-4cd8-8a2d-bd88abdd3c34)

#### Done when:

"Download" button functions as a "Filter" AND "Download".

**Comment by elisekalstad** [comment]
@msprenke -- Is this one straight-forward enough to move to "ready for dev"? Or does it need a more thorough PRD/TDD?

**Comment by msprenke** [comment]
I'll move to ready for dev as it appears straight forward and logical to make the download button always apply any filter input before pulling the data but I think we should run it through product design first to get buy in from the other orgs @isabelcshaw

**Comment by msprenke** [comment]
Ran this by Product Design and there were no objections.  Good to go

**Comment by devin-civi** [comment]
Quick update, I looked into this and it's a little tricky. The most straight forward way to implement this is to do a filter on every download, even if no filter is specified (or an existing filter wasn't changed). But this has the following downsides:

1) It's a little slower on average due to the (often unnecessary) filter.
2) The filter resets the current selected program. (So now download will always reset the selected program, where previously it didn't).

To fix this, we could one or both of the following:
1) Add some javascript to track if the filter has changed and only re-load the page when a filter is needed.
2) Add some extra code to try to keep selected program between filters (if the program is still in the set of results)

Overall I do not think the downsides are worth the complexity of the fix for them. So my plan is to implement the straight forward approach (always filter when download is pressed, even if no new filter is entered). But let me know if there are any concerns with this.

**Comment by msprenke** [comment]
Yes, apply filter, then trigger download.  We'll see how it tests. Thank you.
