### ISSUE TITLE
"English" is always selected in the language dropdown menu

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8477]
Seeing clicking on languages and selecting one will flash the new language momentarily and update the language but then when you click the dropdown again, english is still selected

[Slack Message](https://civiform.slack.com/archives/C01QKN2UNMA/p1725468219012299?thread_ts=1725468051.919329&cid=C01QKN2UNMA)

Discovered by Danielle

**Comment by ssandbekkhaug** [comment]
# Question

Would we rather:
a) Match the legacy UI and remove "Language" from this button. When the user clicks, the user's language (e.g. "English" or "日本語") is shown and selected.
b) Put the string "Language" on the button. When the user clicks, "Language" is shown and selected.

# Details
In the legacy UI, the language selector shows the selected language such as "English" or "日本語".

In the North Star mocks, the language selector is a button that shows "Language".

## Technical Notes
* Dropdown menus show the selected option. So if the user has selected "日本語", the string "日本語" is shown in the button.
* We could add an option in the dropdown menu for "Language". A few options:
  * disabled -> "Language" is not selectable. It is visible. The dropdown menu selects the next language in the UI, which is a bug.
  * hidden -> "Language" is not selectable nor visible, so the the dropdown menu selects the next language in the UI, which is a bug.
  * visible -> "Language" is selectable and visible, so the dropdown menu selects "Language". However, the user's language is not selected, which could look weird.
  * Out of these options, visible is the least bad.

The simplest solution is to match the legacy UI and remove "Language" from this button. The user's language would always be shown.

**Comment by sijiayam** [comment]
The North Star mocks are following the guidance from [USWDS on selecting multiple languages](https://designsystem.digital.gov/patterns/select-a-language/three-or-more-languages/). I have found an example that we could mimic, see https://www.vote.gov/

Although the USWDS page recommends labeling it "Language", I think this is tricky when we select a language other than English. What gets displayed, the word for "language" in that other language? What about when it is in English. I am proposing a solution below.

Expected behavior:
- The language dropdown is labeled Select language
- When a language is selected, the button displays "Select language" in corresponding language
- see https://www.vote.gov/
