### ISSUE TITLE
"You may be eligible" tag shows up before adding any information

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8479]
"You may be eligible" tag shows up on the start here program or any other program when opening it and before adding any information

[Slack Message](https://civiform.slack.com/archives/C01QKN2UNMA/p1725468326089749?thread_ts=1725468051.919329&cid=C01QKN2UNMA)

Discovered by Danielle.

Is this intentional?

**Comment by sijiayam** [comment]
@melanie-exygy @ssandbekkhaug This is a bug that is in North Star and live as well.

I believe this bug was created when we replaced the "you may be eligibile" tag with the toast. A feature gwen was working on I believe.

- The "You may be eligible" alert should only show after an eligibility question has been shown.
- It should only display once on the page after the eligibility question has been shown rather than on every page after.

@isabelcshaw Let me know if you have any thoughts on the behavior.

**Comment by ssandbekkhaug** [comment]
Sijia also mentioned this bug is probably live (not just north star)

**Comment by dkatzz** [comment]
Confirming this is a bug in live and north star. Charlotte also flagged this today as something they noticed as being confusing.

**Comment by melanie-exygy** [comment]
@sijiayam @isabelcshaw, would it be safe to say that we never want to show this alert if the program is a pre-screener?  Sijia, when you say the "alert should only show after an eligibility question has been shown", do you mean "after an eligibility question has been answered (and saved)"?

**Comment by megan0422** [comment]
@melanie-exygy I don't know if my insights are helpful here, but in Charlotte we really don't want that message to ever show on our pre-screener. The goal of our pre-screener is to guide someone to a program that they may be eligible for when they come on not knowing what to apply for. I think showing that message is confusing in a pre-screener because it inadvertently sends the message to a resident that the pre-screener itself is a program application that they can get assistance from.

**Comment by melanie-exygy** [comment]
> @melanie-exygy I don't know if my insights are helpful here, but in Charlotte we really don't want that message to ever show on our pre-screener. The goal of our pre-screener is to guide someone to a program that they may be eligible for when they come on not knowing what to apply for. I think showing that message is confusing in a pre-screener because it inadvertently sends the message to a resident that the pre-screener itself is a program application that they can get assistance from.

Thanks, @megan0422, that is really helpful to know!  That's my understanding of the pre-screener as well.

**Comment by isabelcshaw** [comment]
Thanks so much for jumping in on this all! Agreed that this is a bug and that we should never show this alert in the pre-screener bc a resident is not actually triggering any eligibility criteria for that form. And aligned with the behaviors Sijia shared above. 

One case to clarify is how this works if it's the second application and we know that they are eligible before they even start because we are reusing their data. I'd still like us to maintain the behavior Sijia shared: "It should only display once on the page after the eligibility question has been shown rather than on every page after" if possible for consistency. But if this represents added complexity for some reason, I'm ok to compromise here for now.
