### ISSUE TITLE
Clicking on the View Details link in the Program card doesn't go anywhere

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8498]
Clicking on the View Details link in the Program card doesn't go anyhere. The href is _blank so it looks like it's just opening a new tab redirecting to the homepage

[Slack Message](https://civiform.slack.com/archives/C01QKN2UNMA/p1725469627505189?thread_ts=1725468051.919329&cid=C01QKN2UNMA)

Reported by Jay

![AFvgL4pGPFyDJRf](https://github.com/user-attachments/assets/55496bf3-8a19-467e-b619-58fbe7eda65c)

**Comment by ssandbekkhaug** [comment]
Open question: If the program admin did not set a link for "View details", what should the button do?

**Comment by melanie-exygy** [comment]
> Open question: If the program admin did not set a link for "View details", what should the button do? Should we hide the button?

With the North Star flag off, it looks like the expected behavior in that case is to open a new tab with the program details page.  For example, the path for a program with an id of 134 would be /programs/134.  That page currently looks something like this:  
![image](https://github.com/user-attachments/assets/32fcaa22-f8f0-4880-b9fa-3813feef7f4e)
