### ISSUE TITLE
Console error when selecting program category

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8553]
**Describe the bug**
Console error when selecting program category.

As far as I can tell, the user does not see anything unless they open the console.

**To Reproduce**

1. Log in as admin
2. Create a new program
3. Click on a program category
4. See error in console

**Expected behavior**
No error occurs

**Screenshots**

<img width="2144" alt="console_error" src="https://github.com/user-attachments/assets/c2eca1ad-bfff-45d6-b3c0-84377bcc5e7d">

**Desktop (please complete the following information):**

- OS: Mac OS X
- Browser: Chrome
- Version: 128.0.6613.120

**Additional context**
n/a

**Comment by melanie-exygy** [comment]
This bug was fixed in PR #8656 where the category checkbox element ids were changed so that they no longer collide with that of the filter chip elements on the homepage.   That prevents [this listener](https://github.com/civiform/civiform/blob/5aa7cf4044fa1285846435ff01845fb9708c25ea/server/app/assets/javascripts/main.ts#L363) from being created when on the admin edit page.
