### ISSUE TITLE
[North star] application submission status and date missing on the "My applications" tiles

### ISSUE THREAD

**Issue by haltmar** [civiform/civiform#9064]
**Describe the bug**
application submission status and date missing on the "My applications" tiles on "Find programs" page.

**To Reproduce**

1. Go to Find programs
2. Click on Apply
3. go through the application steps and submit the application
4. on main branch, submission status and timestamp is shown 
<img width="492" alt="image" src="https://github.com/user-attachments/assets/5340d6f1-db9c-4685-a222-80b86b6c2d02">
But in North Star UI, submission status and date is not shown: 
<img width="1055" alt="image" src="https://github.com/user-attachments/assets/44b6229d-2c2f-473e-9caa-d8c1ac5b6f50">

**Expected behavior**
Submission status and timestamp should shown to the applicant. 

**Screenshots**
See screenshots above in the steps to reproduce section

**Desktop (please complete the following information):**

OS: MacOS 14.7 (23H124)
Browser: Chrome Version 130.0.6723.70 (Official Build) (arm64)

**Smartphone (please complete the following information):**
Not tested

**Additional context**

**Comment by melanie-exygy** [comment]
Hi @haltmar, this isn't a bug, it's just a part of the North Star that hasn't been finished yet.  That work will be done in:  #8724 .  I'm going to close this bug since the work is already accounted for in another issue.  When testing the North Star, please note that it is a work in progress and that some pages really aren't ready for testing (such as the homepage).

**Comment by haltmar** [comment]
ACK
